(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"index_atlas_P_", frames: [[230,222,117,126],[0,222,228,120],[0,0,357,220]]},
		{name:"index_atlas_NP_", frames: [[232,252,168,61],[0,252,230,99],[0,0,970,250]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.billboardcinnamonbuns = function() {
	this.spriteSheet = ss["index_atlas_P_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.billboardcranberries = function() {
	this.spriteSheet = ss["index_atlas_NP_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.billboardgreens = function() {
	this.spriteSheet = ss["index_atlas_P_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.billboardpotatoes = function() {
	this.spriteSheet = ss["index_atlas_NP_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.billboardtable = function() {
	this.spriteSheet = ss["index_atlas_NP_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.billboardturkey = function() {
	this.spriteSheet = ss["index_atlas_P_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.wholefoodsmarket = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMCRQgMgEgJgHQgJgJgDgMQgEgOABglIAAiAIgXAAIgGgCIgDgGIAAgGQAAgIAZgVIAKgJIAKgIQAZgWAJAAIAHACQADACgBAEIAAAtIA2AAQAGAAADADQACABAAAIIAAAFQAAAGgDADQgCADgGAAIgxAAIgEACIgCAFIAAB4QABAfAFAIQAFAHAOABQAIgBAMgDIARgEQAEAAAEADQAEADgBAFQAAAOgUAMQgVAMgZAAQgOAAgMgEg");
	this.shape.setTransform(222.6,-10.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhOBbQgjgjAAg0QAAg4AkgkQAjglA2AAQAvAAAcAbQAbAaAAAtQgBAPgEAFQgEAFgSAAIhcAAQgJAAgDgEQgFgEAAgHQAAgGAFgDQAEgEAHAAIAzAAIALgCQADgCABgFQgBgXgPgQQgPgQgWAAQgdAAgOAZQgOAZAAAkQAAAlATAbQAUAcAdAAQASAAAMgEQANgEALgIIAJgHQAMgKAHAAQAFAAAEADQADAEAAAFQAAAFgFAJQgHAIgKAJQgVARgUAIQgTAHgXAAQgzAAgigjg");
	this.shape_1.setTransform(201.1,-8.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABPCxIgLgCQgKgEgXgdIgKgOIgEgFQg7hMgFAAQAAAAgBAAQAAAAgBABQAAAAgBABQAAAAAAABIgBAKIAAALIABAyQACAOADAEIAOAHQALAFAAAKQAAAIgMAEQgMAFggAAQgkAAgMgFQgMgDAAgLQAAgJAMgEIAGgCQAHgEADgMQACgMAAgbIAAgfIAAglIAAgdIgChaQgBgWgEgFQgDgCgLgEIgIgCIgJgEIgCgHQAAgGAFgEQAFgEARgGIAggJIAZgEQAIABADAEQADAFAAALIgCAvIgBA+IAAA8IABAMQAAABAAAAQABABAAAAQABAAAAAAQABAAAAAAIALgFIARgOIAXgXQAGgHAAgEQAAgCgJgFQgIgEAAgIQAAgKAMgFQANgFAiABQAXgBALAFQAKAFAAAJQAAALgRAEQgSAFgHAEQgJAGgVATIgEAFIgIAJIgCAEQAAAEAVAdIADACIApA0QARATAKAHQAGAFAPAEQAQAFAAAKQAAAKgLAFQgMAFgaAAg");
	this.shape_2.setTransform(175.7,-14);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhJB4QgLgEAAgLQAAgIALgEIAHgDQAGgEADgIQACgIAAgSIAAgQIAAgUIAAgOQgBgsgBgNQgCgOgFgDIgLgEQgPgEAAgJQAAgFAFgEQAEgEAKgFIAhgKIAVgFQANAAAEAhIAAAFIABABQANgTANgLQAOgKANAAQARAAAKAKQAKAKAAARQAAARgIAKQgHAJgOAAIgMgCIgKgHIgGgKQgDgGgCAAQgRAAgGAXQgGAXAABJQAAAVACALQACAKAHADIAKADQAOAFAAAKQAAAJgNAEQgOAEggAAQglAAgMgEg");
	this.shape_3.setTransform(152.7,-8.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AArByIgNgNIgKAFQgeAUgeAAQgjAAgWgUQgVgVAAghQAAgnAcgVQAcgVAyAAQAMAAAGADQAGAEAAAKQAAANgRgBQgXABgPAMQgOALAAAUQAAAUAMALQANAMAVAAQAXAAAKgKQAKgLAAgZIAAhcQAAgVgJgLQgJgMgRAAQgLAAgLAFQgKAFgJAMIgFAGQgPASgQABQgKgBgGgGQgFgGAAgLQAAgWAcgPQAcgQAsAAQAaAAATAHQATAHALANQAHAKADAPQADAOAAAjIAABNQAAAOACAGQADAHAFABIAHACQAPAFAAAIQAAALgQAKQgQAJgWAAQgKAAgMgMg");
	this.shape_4.setTransform(130.3,-8.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("ABbCqQgOgEAAgKQAAgKAPgGIAKgGQAFgDACgKQABgLAAggIAAgNIAAhnIgBg8IgeBPQhHC5gQAAQgIAAgOgZQgNgZgjhPIg0h5IgCBfIgBBBIABAtQACAKAEADIALAGQAPAGAAAKQAAAJgNAFQgNAFgdAAQgagBgMgFQgMgEAAgKQAAgJANgGQANgGACgEQACgMAFg/QADg9AAhMIAAgIQAAgZgCgJQgDgJgFgDIgLgFQgQgFAAgKQABgKAKgEQAMgDAiAAIAiAAIAKACQAFAEARArIANAiIAHARQA7CRAEAAQAFAAAWg0QAWgzAehVIAEgPQAJgbAHgHQAEgFALgCIAggBQAhAAAKADQALAEAAAKQAAAKgNAEIgHAEQgHADgDAKQgCAJAAAlIACCKQADA+ACAJQABAFALAEIAFACIAJAGQADADAAAGQAAAKgNAEQgOAFgoAAQgjAAgNgFg");
	this.shape_5.setTransform(95.3,-13.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgSB+IgZgFIgIAFIgHABIgFgBIgFgDQgIgHgHgUQgHgTAAgSQAAgIAEgFQAEgFAGAAQAMAAALATIAJAPQAHAKANAFQAMAGAOAAQAQAAAJgIQAJgIAAgOQAAgUgngUIgOgGQgmgTgNgPQgNgQAAgXQAAgfAVgUQAWgUAjAAIARABIARADIALgEIAIgCQALAAAMATQALATAAAVQAAAJgEAFQgEAEgGAAQgGAAgFgEQgGgFgHgMQgJgOgKgGQgJgGgOAAQgNAAgJAIQgIAHAAANQAAALAJAJQAIAIAeAPIACACQBEAgAAAnQAAAigaAWQgaAXgnAAg");
	this.shape_6.setTransform(49.6,-8.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhpCSQgdghAAg0QAAg7AhgkQAhglAzAAIARACQAIACAEAGQAEAFAAAGQAAANgQAAIgHgBIgGAAQgbAAgQAWQgQAVAAAmQAAApASAZQARAaAbAAQAZAAAOgOQAOgOAAgbIAAhCIAAhvQAAgRgDgGQgDgHgJgDIgHgCQgPgEAAgJQAAgGAGgFQAGgFASgGIAbgIIAXgDQAIAAAEAFQADAEAAALIAAAMIgDCVIACBlQABAXAEADIARAGQANACAAAJQAAALgjAMIgYAGIgTACQgHAAgDgEQgDgEAAgIIAAgLIAAgFIgBgCIgIAFIgKAIQgPALgNAFQgOAGgPAAQgtAAgcghg");
	this.shape_7.setTransform(25.8,-13.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhXBaQgjgjAAg2QAAg2AlgkQAkgkA1AAQA0AAAhAiQAiAiAAA1QAAA3gkAlQgkAmg0AAQg0AAgigkgAgthHQgPATAAAhQAAAvAUAgQAVAgAcAAQAXAAAPgUQAPgUAAggQAAgvgVggQgUgggcAAQgYAAgOAUg");
	this.shape_8.setTransform(-3,-8.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AhXBaQgjgjAAg2QAAg2AlgkQAkgkA1AAQA0AAAhAiQAiAiAAA1QAAA3gkAlQgkAmg0AAQg0AAgigkgAgthHQgPATAAAhQAAAvAUAgQAVAgAcAAQAXAAAPgUQAPgUAAggQAAgvgVggQgUgggcAAQgYAAgOAUg");
	this.shape_9.setTransform(-30.1,-8.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ah6CtQgNgFAAgLQAAgJAMgFQANgFADgEQADgEACgkIACheIgChZQgDglgCgEQgDgDgMgGQgNgFAAgLQAAgJALgDQALgEApAAICUAAIAXgDIANgCIAGABIAEAEQAFAKAFAQQAEARAAALQAAALgEAGQgEAGgHAAQgIAAgKgRIgIgLQgFgIgLgDQgKgFgQAAIgiAAQgWABgMACQgMADgEAFQgEAFgCAQIgCAvIAAATQAAAMACACQACADAHAAIAnAAQATAAAIgGQAHgFACgPIABgFQAEgYANAAQAKAAAEAMQAEAOAAAuQAAAugEAMQgEANgKABQgNAAgEgaIgBgEQgCgQgHgFQgIgGgTABIgnAAQgGgBgDAFQgCAEAAAPIAAASIACBFQABAOAFADIAKAFQAPAGAAAKQAAAKgNAFQgOAEglAAQgnAAgNgEg");
	this.shape_10.setTransform(-57.9,-13.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhOBbQgjgjAAg0QAAg4AkgkQAkglA1AAQAvAAAcAbQAbAaAAAtQAAAPgFAFQgEAFgSAAIhcAAQgJAAgEgEQgEgEAAgHQAAgGAEgDQAFgEAHAAIAyAAIAMgCQAEgCAAgFQAAgXgQgQQgPgQgWAAQgdAAgOAZQgOAZAAAkQAAAlAUAbQATAcAdAAQASAAAMgEQANgEALgIIAJgHQAMgKAHAAQAFAAAEADQAEAEAAAFQgBAFgFAJQgHAIgKAJQgVARgTAIQgUAHgXAAQgyAAgjgjg");
	this.shape_11.setTransform(-98.9,-8.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgoCtQgMgDAAgLQAAgHAKgFIAMgHQAEgDACgQIACgvIAAgmIAAgtIAAgSQAAg9gCgSQgDgRgFgDIgPgGQgPgDAAgJQAAgGAFgEQAEgEARgGIAhgJIAYgEQAIABACAEQADAFAAALIAAATQgDBVAABYIABBRQACASAEAEIANAHQAMAFAAAKQAAAIgMAEQgNAFgfAAQgjAAgMgFg");
	this.shape_12.setTransform(-118.8,-14);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AhXBaQgjgjAAg2QAAg2AlgkQAkgkA1AAQA0AAAhAiQAiAiAAA1QAAA3gkAlQgkAmg0AAQg0AAgigkgAgthHQgPATAAAhQAAAvAUAgQAVAgAcAAQAXAAAPgUQAPgUAAggQAAgvgVggQgUgggcAAQgYAAgOAUg");
	this.shape_13.setTransform(-138.8,-8.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAiCtQgMgEgBgJQABgJAMgFIAJgDQAGgEABgKQADgKAAgaQAAhOgKgSQgKgUgZAAQgMAAgMAIQgLAIgHAMQgGAKgCATQgBASAAAwQAAAYABAIQADAIAFADIAJADQAMAFAAAJQAAAJgMAEQgLAEggAAQgmAAgLgEQgMgEAAgKQAAgIAMgFIAGgDQAGgDADgKQADgKAAgbIAAgnIAAglIgBhtQgCgbgEgFQgCgDgPgEQgOgEAAgIQAAgHAGgFQAGgEAVgIIAZgHIAVgCQAJAAADAEQADAFAAALIAAAKIgCBgIAAAMIACAGIADACIAFgGIAJgKQAMgLAOgGQAMgGAPAAQAqAAAUAbQAVAagBA2IAAAWIABAsIAAANQAAANACAFQACAFAGADIAGADQAMAEAAAJQAAAKgLAEQgMAEgnAAQgfAAgLgEg");
	this.shape_14.setTransform(-167.1,-14);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAhBVIgziGQgQgsgJgUQgKgUgJgHIgOgGQgMgEAAgJQAAgKAMgEQALgEAuAAQAsAAAMAEQALAEAAAKQAAAJgSAHIgDABQgFACgDADQgDAEAAAFQAAAJAMAhIAoBpIARAmQAFALAEAAQADAAAFgIIAQgkIAEgKQAyh4AAgOQAAgIgDgFQgEgFgIgEIgFgCQgPgGAAgJQAAgKAKgEQAKgEAnAAQAmAAAKAEQAKAEAAAKQAAAJgOAGIgKAFQgRALggBTIgUAxIguByIgIAVQgPAngLAAQgMAAgkhdgAhjCdIgDgHQgfhDgvh8IgXg6IgOgdQgGgKgIgEIgHgDQgPgEAAgKQAAgKALgEQALgEAuAAQAuAAALAEQALAEAAAKQAAAJgSAHIgCABQgGACgDADQgCAEAAAFQAAAIAJAdIApBqIATAsQAFAJADAAQAFAAAFgMIAMgcQAFgQANAAQAPAAAAAQIgDAPIgfBNIgHATQgPAngKAAQgIAAgJgVg");
	this.shape_15.setTransform(-206,-13.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.wholefoodsmarket, new cjs.Rectangle(-233,-44.7,466.1,61.4), null);


(lib.trynewflavors = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgSB+IgZgFIgIAFIgHABIgFgBIgFgDQgIgHgHgUQgHgTAAgSQAAgIAEgFQAEgFAGAAQAMAAALATIAJAPQAHAKANAFQAMAGAOAAQAQAAAJgIQAJgIAAgOQAAgUgngUIgOgGQgmgTgNgPQgNgQAAgXQAAgfAVgUQAWgUAjAAIARABIARADIALgEIAIgCQALAAAMATQALATAAAVQAAAJgEAFQgEAEgGAAQgGAAgFgEQgGgFgHgMQgJgOgKgGQgJgGgOAAQgNAAgJAIQgIAHAAANQAAALAJAJQAIAIAeAPIACACQBEAgAAAnQAAAigaAWQgaAXgnAAg");
	this.shape.setTransform(166.8,-8.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhJB4QgLgEAAgLQAAgIALgEIAHgDQAGgEADgIQACgIAAgSIAAgQIgBgUIAAgOQAAgsgBgNQgCgOgFgDIgLgEQgPgEAAgJQAAgFAFgEQAEgEAKgFIAhgKIAVgFQANAAADAhIABAFIABABQAMgTAOgLQANgKAOAAQARAAAKAKQAKAKAAARQAAARgHAKQgIAJgOAAIgMgCIgKgHIgGgKQgDgGgCAAQgRAAgGAXQgGAXAABJQAAAVACALQADAKAGADIAKADQAOAFAAAKQAAAJgNAEQgOAEggAAQglAAgMgEg");
	this.shape_1.setTransform(147.9,-8.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhXBaQgjgjAAg2QAAg2AlgkQAkgkA1AAQA0AAAhAiQAiAiAAA1QAAA3gkAlQgkAmg0AAQg0AAgigkgAgthHQgPATAAAhQAAAvAUAgQAVAgAcAAQAXAAAPgUQAPgUAAggQAAgvgVggQgUgggcAAQgYAAgOAUg");
	this.shape_2.setTransform(124.5,-8.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgZBlQgOgXgihQIgOgjQgRgugLgGIgHgDQgOgFAAgJQAAgKAMgEQAMgEAnAAQAhAAAMAEQAMAEAAAKIgCAIIgEAEIgIADQgKAFAAAFIAFATIATAvIATAuQAGALADAAQADAAAFgGIALgWIAag8QAIgXAAgJIgCgIIgFgGIgHgDQgLgEAAgIQAAgJALgEQALgEAeAAQAZAAAKAEQAKAEAAAJQAAAKgMAEIgIADQgMAFgUAwIgGAPIgKAWQg3B9gPAAQgLAAgNgYg");
	this.shape_3.setTransform(98.5,-7.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AArBxIgNgMIgKAFQgeAUgeAAQgjAAgWgUQgVgVAAghQAAgnAcgUQAcgWAyAAQAMAAAGAEQAGADAAAJQAAANgRABQgXgBgPAMQgOAMAAAVQAAASAMAMQANAMAVAAQAXAAAKgLQAKgKAAgaIAAhbQAAgVgJgLQgJgMgRAAQgLAAgLAGQgKAEgJAMIgFAGQgPASgQAAQgKAAgGgFQgFgHAAgKQAAgXAcgPQAcgQAsAAQAaAAATAHQATAHALAOQAHAIADAQQADAPAAAiIAABNQAAANACAHQADAHAFACIAHABQAPAEAAAJQAAAMgQAJQgQAJgWAAQgKAAgMgNg");
	this.shape_4.setTransform(73.3,-8.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgpCuQgLgEAAgLQAAgHAKgFIAMgHQAEgEACgPIACgvIgBglIAAguIAAgTQAAg8gCgRQgCgSgFgDIgPgFQgPgEAAgJQAAgGAFgEQAFgEARgGIAggJIAYgDQAHAAADAEQAEAEAAAMIgBASQgDBXAABXIABBSQACARAEAEIAOAIQALAEAAAJQAAAKgMAEQgNADgfAAQgkAAgMgDg");
	this.shape_5.setTransform(53,-13.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ah6CsQgNgEAAgKQAAgKAMgFQANgFADgEQADgFACgjIACheIgChZQgDglgCgEQgDgDgMgGQgNgFAAgKQAAgKALgEQALgDApAAICUAAIAXgCIANgDIAGACIAEADQAFAKAFAQQAEARAAALQAAALgEAGQgEAGgHAAQgIAAgKgRIgIgMQgFgGgLgFQgKgDgQAAIgiAAQgWgBgMADQgMADgEAFQgEAFgCAQIgCAuIAAAUQAAALACADQACADAHAAIAnAAQATAAAIgFQAHgGACgPIABgFQAEgZANAAQAKAAAEAOQAEAMAAAvQAAAtgEANQgEANgKAAQgNAAgEgZIgBgEQgCgPgHgGQgIgFgTgBIgnAAQgGABgDAEQgCADAAAQIAAATIACBDQABAOAFAEIAKAFQAPAGAAAKQAAALgNADQgOAFglAAQgnAAgNgFg");
	this.shape_6.setTransform(32.3,-13.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAOAaIgdhLQgNgigMgGIgHgDQgOgFAAgJQAAgKAMgEQAMgEAnAAQAhAAALAEQAMAEAAAKIgCAHIgEAFIgIADQgKAFAAAFIAEAQIAUAyIAVAuQAFALADAAQAEAAAEgGIALgWIAag8QAJgXAAgJIgCgIIgGgGIgHgDQgKgEAAgIQAAgJAKgEQALgEAeAAQAZAAALAEQAKAEAAAJQAAAKgNAEIgIADQgLAGgWAyIgFAMIgKAWQg3B9gQAAQgQAAgrhjgAiNAOIgHgQIgQgoQgQgpgKgGIgIgDQgOgFAAgJQAAgKANgEQAMgEAnAAQAhAAALAEQAMAEAAAKIgBAIIgFAEIgIADQgKAFAAAFIAGAUIASAuIAUAtQAGAMADAAQAIAAAGgPIAJgRIAFgHQADgDAFAAQAGAAAEADQADAEAAAGQAAAGgHAOQgZA3gLATQgLASgJAAQgRAAgvhvg");
	this.shape_7.setTransform(-15.5,-7.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhOBbQgigjgBg0QAAg4AkgkQAjglA2AAQAvAAAbAbQAbAaAAAtQAAAPgDAFQgFAFgSAAIhcAAQgJAAgDgEQgFgEAAgHQAAgGAFgDQADgEAIAAIAzAAIALgCQADgCAAgFQAAgXgPgQQgPgQgWAAQgdAAgOAZQgOAZAAAkQAAAlATAbQATAcAfAAQARAAAMgEQANgEAMgIIAIgHQANgKAGAAQAGAAADADQAEAEgBAFQAAAFgFAJQgHAIgKAJQgVARgUAIQgTAHgXAAQgzAAgigjg");
	this.shape_8.setTransform(-48.4,-8.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ah2B4QgMgEAAgLQAAgIAMgFIAGgCQAGgEADgIQACgIAAgSIAAgQIAAgUIAAgYQAAgmgCgLQgCgMgFgDIgLgEQgPgEAAgJQAAgFAFgEQAFgEAKgFIAjgLIAZgEQAHAAADAEQADADAAAIIAAAQIAAADIABAAIACAAIABgBIAFgFIAFgEQAbgZAdAAQASAAAQAIQAQAHALANQALANAFATQAEASAAAnIAAAgIAAAPIAAAOQAAARACAIQADAGAGAEIAGACQAMAFAAAIQAAAKgLAEQgLAEglAAQgiAAgMgDQgLgEAAgJQAAgKAMgEIAJgEQAFgDADgKQACgLAAgaQAAhMgKgUQgKgTgZAAQgMAAgMAIQgMAHgGANQgFALgCASQgCATAAAvQAAAYACAIQACAHAFADIAJAEQAMAEAAAKQAAAJgMAEQgMAEgfAAQglAAgMgEg");
	this.shape_9.setTransform(-75.6,-8.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhvCgQgLgKAAgQQAAgMAIgIQAJgJALAAIALACIAHAFIAHAJQAHAKAEAAQAMAAANgSQAMgSAAgTQAAgVgRgmIgCgGIgmhUIgXgvQgEgIgOgGQgJgEgCgDQgDgDAAgGQAAgKAMgEQANgFAjAAQAkAAAMAEQALAEABAKIgCAHIgFAFIgJAEQgIAEgBAEIAGASIATAwIATAuQAGALADAAQADAAAFgLIARgmIARgwQAGgRAAgGQAAgHgOgIQgOgIAAgGQAAgIAMgEQAKgEAcAAQAdAAAKAEQAKAEAAAKQAAAJgNADIgKAEQgOAHgPApIgHATIgfBNQgoBkgZAeQgZAfgkAAQgRAAgMgKg");
	this.shape_10.setTransform(-115.2,-3.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhJB4QgLgEAAgLQAAgIALgEIAHgDQAGgEADgIQACgIAAgSIAAgQIgBgUIAAgOQAAgsgBgNQgCgOgGgDIgKgEQgPgEAAgJQAAgFAFgEQAEgEAKgFIAhgKIAVgFQANAAADAhIABAFIABABQAMgTAOgLQANgKAOAAQARAAAKAKQAKAKAAARQAAARgHAKQgIAJgOAAIgMgCIgKgHIgGgKQgDgGgCAAQgRAAgGAXQgGAXAABJQAAAVACALQADAKAGADIAKADQAOAFAAAKQAAAJgNAEQgOAEggAAQglAAgMgEg");
	this.shape_11.setTransform(-136.1,-8.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgyCrQgOgDAAgLQAAgKANgFQAOgFACgEQADgDABgoIAChyIgChAIgCgnQgBgGgDgCQgFgCgKAAIgKAAQgRAAgJAEQgJAEgHAKIgIAQIgGAQIgHAHQgFAEgEAAQgHAAgDgHQgEgGAAgPQAAggAHgTQAIgUALAAIAEAAQASADAdAAICOAAQAeAAASgDIAEAAQALAAAIAUQAHATAAAgQAAAPgEAGQgDAHgHAAIgJgEIgHgHIgHgQIgHgQQgHgKgJgEQgKgEgQAAIgKAAQgKAAgFACQgDACgBAHIgDAmIgBBAIACByQABAoADADQADAEANAFQANAFAAAKQAAALgOADQgOAFglAAQgkAAgOgFg");
	this.shape_12.setTransform(-161.6,-13.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.trynewflavors, new cjs.Rectangle(-179.4,-44.5,358.9,61.4), null);


(lib.thanksgiving = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhZCeQgfgTAAgbQAAgMAHgIQAGgIAOAAQAKAAAFAGQAGAFADAMQAGARAPALQAPAKAeAAQAfAAAVgMQAWgNAAgTQAAgKgIgHQgIgGgPAAIgcABIglACQgrAAgXgOQgXgPAAgSQAAgNAIgMQAJgLARgKQgOgMgHgPQgHgRAAgSQAAgoAegZQAdgaAuAAIAYACIAmAHQAIAAALgFQAKgEAQgKIAHAHIADAIQAAALgIAJQgHAJgOAIIAHAUIACATQAAAogdAZQgdAZgvAAIgZgCIgXgFIgIAJIgCAJQAAALALAGQAMAFAYAAIAkgDIAlgCQAigBASAOQASAOAAAaQAAAmgmAaQgmAZg5ABQgugBgfgSgAgnh3QgNAPAAAYQAAAYANAQQAMAPAUAAQATAAAOgPQANgPAAgZQAAgZgNgOQgNgQgUgBQgTABgNAQg");
	this.shape.setTransform(135.6,-4.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ah2B4QgMgEAAgLQAAgIAMgFIAGgCQAGgEADgIQACgIAAgSIAAgQIAAgUIAAgYQAAgmgCgLQgCgMgFgDIgLgEQgPgEAAgJQAAgFAFgEQAFgEAKgFIAjgLIAZgEQAHAAADAEQADADAAAIIAAAQIAAADIABAAIACAAIABgBIAFgFIAFgEQAbgZAdAAQASAAAQAIQAQAHALANQALANAFATQAEASAAAnIAAAgIAAAPIAAAOQAAARACAIQADAGAGAEIAGACQAMAFAAAIQAAAKgLAEQgLAEglAAQgiAAgMgDQgLgEAAgJQAAgKAMgEIAJgEQAFgDADgKQACgLAAgaQAAhMgKgUQgKgTgZAAQgMAAgMAIQgMAHgGANQgFALgCASQgCATAAAvQAAAYACAIQACAHAFADIAJAEQAMAEAAAKQAAAJgMAEQgMAEgfAAQglAAgMgEg");
	this.shape_1.setTransform(107.5,-8.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgqCsQgMgDAAgLQAAgJALgEIAHgCQAGgEACgIQADgIAAgSIAAgQIAAgUIAAgZQAAgmgCgLQgCgLgFgDIgLgEQgPgEAAgJQAAgFAFgEQAEgEALgFIAkgLIAZgFQAGAAAEAFQACAEAAALIAAAOIAAALIgCA9IAAABIgBA8QAAAXACAJQACAKAGADIAJADQAMAFAAAKQAAAIgMAEQgMAFgfAAQglAAgLgFgAgdh5QgKgJAAgNQAAgNALgJQALgLAQAAQAPABALAIQAKAJAAAOQAAAMgLAKQgLAJgQAAQgQAAgKgIg");
	this.shape_2.setTransform(86.2,-13.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgZBlQgOgXgihQIgOgjQgRgugLgGIgHgDQgOgFAAgJQAAgKAMgEQAMgEAnAAQAhAAAMAEQAMAEAAAKIgCAIIgEAEIgIADQgKAFAAAFIAFATIATAvIATAuQAGALADAAQADAAAFgGIALgWIAag8QAIgXAAgJIgCgIIgFgGIgHgDQgLgEAAgIQAAgJALgEQALgEAeAAQAZAAAKAEQAKAEAAAJQAAAKgMAEIgIADQgMAFgUAwIgGAPIgKAWQg3B9gPAAQgLAAgNgYg");
	this.shape_3.setTransform(67,-8.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgqCsQgMgDAAgLQAAgJAMgEIAGgCQAGgEADgIQACgIAAgSIAAgQIAAgUIAAgZQAAgmgCgLQgCgLgFgDIgLgEQgPgEAAgJQAAgFAFgEQAEgEAKgFIAlgLIAZgFQAGAAADAFQADAEAAALIAAAOIgBALIgBA9IAAABIgBA8QAAAXACAJQACAKAFADIAJADQANAFAAAKQAAAIgMAEQgMAFggAAQgjAAgMgFgAgdh5QgLgJAAgNQAAgNAMgJQALgLARAAQAOABALAIQAKAJAAAOQAAAMgLAKQgMAJgQAAQgPAAgKgIg");
	this.shape_4.setTransform(47.5,-13.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhZCeQgfgTAAgbQAAgMAHgIQAGgIAOAAQAKAAAFAGQAGAFADAMQAGARAPALQAPAKAeAAQAfAAAVgMQAWgNAAgTQAAgKgIgHQgIgGgPAAIgcABIglACQgrAAgXgOQgXgPAAgSQAAgNAIgMQAJgLARgKQgOgMgHgPQgHgRAAgSQAAgoAegZQAdgaAuAAIAYACIAmAHQAIAAALgFQAKgEAQgKIAHAHIADAIQAAALgIAJQgHAJgOAIIAHAUIACATQAAAogdAZQgdAZgvAAIgZgCIgXgFIgIAJIgCAJQAAALALAGQAMAFAYAAIAkgDIAlgCQAigBASAOQASAOAAAaQAAAmgmAaQgmAZg5ABQgugBgfgSgAgnh3QgNAPAAAYQAAAYANAQQAMAPAUAAQATAAAOgPQANgPAAgZQAAgZgNgOQgNgQgUgBQgTABgNAQg");
	this.shape_5.setTransform(28.9,-4.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgSB+IgZgFIgIAFIgHABIgFgBIgFgDQgIgHgHgUQgHgTAAgSQAAgIAEgFQAEgFAGAAQAMAAALATIAJAPQAHAKANAFQAMAGAOAAQAQAAAJgIQAJgIAAgOQAAgUgngUIgOgGQgmgTgNgPQgNgQAAgXQAAgfAVgUQAWgUAjAAIARABIARADIALgEIAIgCQALAAAMATQALATAAAVQAAAJgEAFQgEAEgGAAQgGAAgFgEQgGgFgHgMQgJgOgKgGQgJgGgOAAQgNAAgJAIQgIAHAAANQAAALAJAJQAIAIAeAPIACACQBEAgAAAnQAAAigaAWQgaAXgnAAg");
	this.shape_6.setTransform(4.7,-8.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABPCxIgLgCQgKgEgXgdIgKgOIgEgFQg7hMgFAAQAAAAgBAAQAAAAgBABQAAAAgBABQAAAAAAABIgBAKIAAALIABAyQACAOADAEIAOAHQALAFAAAKQAAAIgMAEQgMAFggAAQgkAAgMgFQgMgDAAgLQAAgJAMgEIAGgCQAHgEADgMQACgMAAgbIAAgfIAAglIAAgdIgChaQgBgWgEgFQgDgCgLgEIgIgCIgJgEIgCgHQAAgGAFgEQAFgEARgGIAggJIAZgEQAIABADAEQADAFAAALIgCAvIgBA+IAAA8IABAMQAAABAAAAQABABAAAAQABAAAAAAQABAAAAAAIALgFIARgOIAXgXQAGgHAAgEQAAgCgJgFQgIgEAAgIQAAgKAMgFQANgFAiABQAXgBALAFQAKAFAAAJQAAALgRAEQgSAFgHAEQgJAGgVATIgEAFIgIAJIgCAEQAAAEAVAdIADACIApA0QARATAKAHQAGAFAPAEQAQAFAAAKQAAAKgLAFQgMAFgaAAg");
	this.shape_7.setTransform(-18.3,-14);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ah2B4QgMgEAAgLQAAgIAMgFIAGgCQAGgEADgIQACgIAAgSIAAgQIAAgUIAAgYQAAgmgCgLQgCgMgFgDIgLgEQgPgEAAgJQAAgFAFgEQAFgEAKgFIAjgLIAZgEQAHAAADAEQADADAAAIIAAAQIAAADIABAAIACAAIABgBIAFgFIAFgEQAbgZAdAAQASAAAQAIQAQAHALANQALANAFATQAEASAAAnIAAAgIAAAPIAAAOQAAARACAIQADAGAGAEIAGACQAMAFAAAIQAAAKgLAEQgLAEglAAQgiAAgMgDQgLgEAAgJQAAgKAMgEIAJgEQAFgDADgKQACgLAAgaQAAhMgKgUQgKgTgZAAQgMAAgMAIQgMAHgGANQgFALgCASQgCATAAAvQAAAYACAIQACAHAFADIAJAEQAMAEAAAKQAAAJgMAEQgMAEgfAAQglAAgMgEg");
	this.shape_8.setTransform(-47.1,-8.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AArByIgNgNIgKAFQgeAUgeAAQgjAAgWgUQgVgVAAghQAAgnAcgVQAcgVAyAAQAMAAAGADQAGAEAAAKQAAANgRgBQgXABgPAMQgOALAAAUQAAAUAMALQANAMAVAAQAXAAAKgKQAKgLAAgZIAAhcQAAgVgJgLQgJgMgRAAQgLAAgLAFQgKAFgJAMIgFAGQgPASgQABQgKgBgGgGQgFgGAAgLQAAgWAcgPQAcgQAsAAQAaAAATAHQATAHALANQAHAKADAPQADAOAAAjIAABNQAAAOACAGQADAHAFABIAHACQAPAFAAAIQAAALgQAKQgQAJgWAAQgKAAgMgMg");
	this.shape_9.setTransform(-74,-8.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAhCtQgLgEgBgJQABgJALgFIAKgDQAFgEACgKQACgKABgaQAAhOgKgSQgKgUgZAAQgMAAgMAIQgMAIgGAMQgFAKgDATQgBASAAAwQAAAYABAIQACAIAGADIAJADQAMAFAAAJQAAAJgMAEQgMAEgfAAQgmAAgLgEQgMgEAAgKQAAgIAMgFIAGgDQAGgDADgKQADgKAAgbIAAgnIAAglIgChtQgBgbgEgFQgCgDgPgEQgOgEAAgIQAAgHAGgFQAFgEAWgIIAZgHIAVgCQAJAAADAEQADAFABALIgBAKIgCBgIAAAMIACAGIADACIAFgGIAJgKQAMgLAOgGQAMgGAPAAQAqAAAUAbQAVAaAAA2IAAAWIAAAsIAAANQAAANACAFQACAFAGADIAGADQAMAEAAAJQAAAKgLAEQgMAEgnAAQgfAAgMgEg");
	this.shape_10.setTransform(-101.9,-14);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgyCsQgOgFAAgKQAAgKANgFQAOgFACgEQADgDABgoIABhyIgBg/IgCgoQAAgGgFgCQgDgCgKAAIgLAAQgQAAgKAEQgJAEgHAJIgIAQIgHARIgGAIQgFACgEAAQgHAAgDgGQgEgHAAgOQAAggAHgUQAIgTALAAIADAAQAUADAdAAICNAAQAeAAASgDIADAAQAMAAAHATQAIAUAAAgQAAAOgDAHQgEAGgHAAIgIgCIgIgIIgHgRIgIgQQgGgJgJgEQgKgEgQAAIgKAAQgLAAgEACQgDACgCAHIgCAnIgBA/IACByQACAoACADQADAEANAFQANAFAAAKQAAAKgOAFQgNAEgmAAQglAAgNgEg");
	this.shape_11.setTransform(-131.6,-13.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.thanksgiving, new cjs.Rectangle(-149.5,-44.7,299,61.4), null);


(lib.tastingeventnearyou = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgWBAQgLgEgIgHQgHgIgFgKQgDgFAAgGIgBgMIAAgkIAAgkQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBABAAIADgCIAGgBIAEAAIAGACQACABAAADIAABEQABAHACAHQACAHAEAGQAFAFAGADQAHADAHAAQAIAAAHgDQAGgDAFgFQAEgFACgIQACgHAAgHIAAhEQAAgDADgBQADgDADAAIAEAAIAGABIADADQABAAAAAAQABABAAAAQAAABAAAAQABABAAABIAABIIgCAMQgBAGgDAFQgEAKgIAIQgIAHgKAEQgLAEgMABQgLgBgLgEg");
	this.shape.setTransform(106.3,-8.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgNBDIgOgEQgGgCgGgEIgKgIQgKgKgFgMQgDgGgBgHQgCgHAAgHQAAgGACgHQABgHADgGQAFgNAKgJIAKgIIAMgHIAOgEIANgBIAOABIAOAEQAMAGAKAJQAKAJAFANQAGAMAAAOQAAAHgCAHIgEANQgFAMgKAKQgKAJgMAFIgOAEQgHACgHAAIgNgCgAgQgpQgIADgHAGQgGAHgEAIQgDAIAAAJQAAAJADAJQAEAIAGAGQAHAGAIAEQAIADAIAAQAJAAAIgDQAIgEAGgGQAHgGADgIQAEgJAAgJQAAgJgEgIQgDgIgHgHQgGgGgIgDQgIgEgJAAQgIAAgIAEg");
	this.shape_1.setTransform(91.1,-8.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgFBFIgDgBIgCgCIgBgCIAAgvIgCgHIgDgHIgmg6IAAgCQAAAAAAgBQAAgBABAAQAAgBAAAAQAAAAABgBIAEgDIAFgCIAEgBIAEABQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAbArIACADIADAAIADgBIACgCIAbgrQAAAAAAgBQABAAAAgBQABAAAAAAQABgBAAAAIAFgBIAEABIAFACIAEADIACAEIAAABIgBACIgmA6IgDAIIgBADIAAACIAAAvQgCAFgEABIgIAAg");
	this.shape_2.setTransform(77.3,-8.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAhBDIgDgBIgDgBIgBgBIgXgkIgDgEQgDgBgDAAIgRAAIgFABQgCACAAADIABAhQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAIgEACIgFAAIgFAAQgEAAgCgCQgCgBAAgEIAAh5QAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAQABAAAAAAIA4AAQAKAAAIADQAJADAGAGQAGAGAEAIQAEAIAAALQAAALgFAHQgEAGgFAEIgJAHQgEADAAADIAAADIAFAHIAIALIAHAKIADAHQAAAAAAABQgBABAAAAQAAABAAAAQgBAAAAABIgEADIgFACIgFAAgAgbgqQgDACAAAEIAAAdQAAAEADACQADABADAAIAbAAQAFAAAEgBIAIgEQAEgCACgEQABgFAAgFQAAgLgHgGIgIgEQgEgBgFAAIgbAAIgGABg");
	this.shape_3.setTransform(59.5,-8.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAwBCIgHAAQgDgBgCgDIgHgSIgDgDIgDgBIgsAAIgCAAIgCACIgCABIgBABIgHASIgCACIgEABIgEABIgEAAIgDAAIgEAAIgEgCQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIA2h8QAAgBAAAAQABAAAAgBQABAAAAAAQABgBAAAAIAEgBIAFABQAEAAABADIA0B8IAAABQAAAAAAAAQAAABAAAAQAAABgBAAQAAAAAAAAIgEABIgFABgAgCgSIgBADIgDAHIgEAHIgDAHIgCAFIgBADIABADQABAAAAABQAAAAAAAAQABAAAAAAQAAAAABAAIAZAAIADAAIABgDIgCgGIgEgKIgFgMIgDgGIgDgBIgBAAg");
	this.shape_4.setTransform(45.7,-8.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgsBCIgEgCQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAAAIAAh5QAAgBAAAAQABgBAAAAQAAgBAAAAQABAAAAgBIAEgBIBcAAIADACIABAEIABAFIgBAEIAAAFIgEADIhEAAIgEACIgBAEIAAASQAAABAAAAQAAABAAAAQAAABABAAQAAABAAAAQABABAAAAQABAAAAAAQABABABAAQAAAAABAAIArAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABIACAEIAAAGIAAADQAAAFgFACIgrAAQgCAAgCACQgBABAAAAQAAABgBAAQAAABAAABQAAAAAAABIAAAUQAAAAAAABQAAABAAAAQAAABABAAQAAABAAAAQABABAAAAQABAAAAAAQABABAAAAQABAAABAAIBDAAQAEACAAAFIAAAEIAAAGIgCAEQAAABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_5.setTransform(33.6,-8.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAmBFQgCgBgCgDIg2hKQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgEABQAAABgBAAQAAAAAAABQAAAAAAABQAAAAAAABIAABDQgCAEgDABIgGABIgIgBQgEAAgCgFIAAh8QAAgBABAAQAAgBAAAAQAAAAAAgBQABAAAAAAIAEgCIAEgBIAFAAQAFAAAEAEIA1BIIADABIACgBIACgCIAAhDQAAAAABgBQAAAAAAgBQABAAAAgBQAAAAABAAIAEgCIAFAAIAEAAQAHAAABAFIAAB+IgDAEQgDACgDAAg");
	this.shape_6.setTransform(19.5,-8.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AACBDIgEAAIgGgBQgDgCAAgEIAAhhQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBgBAAAAQgBgBgFAAIgLgBIgKAAIgFABQgEAAgBgEIgBgGIAAgEIAAgEIACgEQABAAAAgBQAAAAABAAQAAAAABAAQABgBAAAAIBbAAQADAAACADIABAGIAAAFIgBAEIgCAEQAAAAgBABQAAAAAAAAQgBAAgBAAQAAABgBAAIgaAAIgFABQgCABAAAEIAABgQAAABAAAAQAAABAAABQAAAAgBABQAAAAgBABIgDACg");
	this.shape_7.setTransform(1.5,-8.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAnBFQgDgBgDgDIg1hKQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgEABQAAABgBAAQAAAAAAABQAAAAAAABQAAAAAAABIAABDQgCAEgDABIgGABIgIgBQgEAAgCgFIAAh8QAAgBABAAQAAgBAAAAQAAAAAAgBQABAAAAAAIAEgCIAEgBIAFAAQAGAAADAEIA1BIIADABIACgBIACgCIAAhDQAAAAABgBQAAAAAAgBQABAAAAgBQAAAAABAAIAEgCIAFAAIAEAAQAHAAABAFIAAB+IgDAEQgCACgEAAg");
	this.shape_8.setTransform(-11,-8.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgsBCIgEgCQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAAAIAAh5QAAgBAAAAQABgBAAAAQAAgBAAAAQABAAAAgBIAEgBIBcAAIADACIABAEIABAFIgBAEIAAAFIgEADIhEAAIgEACIgBAEIAAASQAAABAAAAQAAABAAAAQAAABABAAQAAABAAAAQABABAAAAQABAAAAAAQABABABAAQAAAAABAAIArAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABIACAEIAAAGIAAADQAAAFgFACIgrAAQgCAAgCACQgBABAAAAQgBABAAAAQAAABAAABQAAAAAAABIAAAUQAAAAAAABQAAABAAAAQAAABABAAQAAABAAAAQABABAAAAQABAAAAAAQABABAAAAQABAAABAAIBDAAQAEACAAAFIAAAEIAAAGIgCAEQAAABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_9.setTransform(-23.7,-8.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgCBAIgEgIIgGgPIgJgTIgJgVIgJgTIgIgTIgFgNIgCgHIACgEIAEgCIAFgCIAEgBQADABADACQACABABACIAbBDIACACIABAAQADAAABgDIAahCIAEgEQADgDACAAIAFABIAFACIAEADIACADIgCAGIgGANIgIATIgJAVIgJAVIgIATIgHAPIgDAIIgBACIgCABQAAAAAAAAQgBAAAAAAQAAgBgBAAQAAgBAAgBg");
	this.shape_10.setTransform(-36.6,-8.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgsBCIgEgCQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAAAIAAh5QAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBIAEgBIBcAAIADACIABAEIABAFIgBAEIAAAFIgEADIhEAAIgEACIgBAEIAAASQAAABAAAAQAAABAAAAQAAABABAAQAAABAAAAQABABAAAAQABAAAAAAQABABABAAQAAAAABAAIArAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABIACAEIAAAGIAAADQAAAFgFACIgrAAQgCAAgCACQgBABAAAAQAAABgBAAQAAABAAABQAAAAAAABIAAAUQAAAAAAABQAAABAAAAQAAABABAAQAAABAAAAQABABAAAAQABAAAAAAQABABAAAAQABAAABAAIBDAAQAEACAAAFIAAAEIAAAGIgCAEQAAABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_11.setTransform(-48.2,-8.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgKBDQgHgBgGgDIgNgGIgKgIIgJgKQgEgFgCgHQgGgNAAgOQAAgHABgGQACgHADgGQAGgNAJgJIAKgIIANgHIANgEIANgBQAIAAAIACQAHABAHADQAOAHAKAMIABACIgCAEIgFAFIgEAEIgFABQgDAAgCgDIgHgGQgFgDgGgDQgHgDgJAAQgIAAgIAEQgJAEgGAGQgGAGgEAIQgDAJAAAIQAAAJADAIQAEAJAGAGQAGAGAJAEQAIAEAIAAIAKgBIAJgCQAEgCAEgDQAEgCACgFIABgCQAAAAgBgBQAAgBAAAAQAAgBgBAAQAAgBgBAAIgEgBIgYAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBAAAAgBIgBgEIgBgFIAAgEIABgFQABgCADgBIA3AAIADABIACACQACAFAAAHIgBAGIAAAFQgEAKgHAIQgGAHgJAGQgIAFgKADQgKADgKAAIgNgCg");
	this.shape_12.setTransform(-68.8,-8.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAnBFQgDgBgDgDIg1hKQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgEABQAAABgBAAQAAAAAAABQAAAAAAABQgBAAAAABIAABDQgBAEgDABIgGABIgIgBQgEAAgCgFIAAh8QAAgBABAAQAAgBAAAAQAAAAAAgBQABAAAAAAIAEgCIAEgBIAFAAQAFAAAEAEIA1BIIADABIADgBIABgCIAAhDQAAAAABgBQAAAAAAgBQABAAAAgBQABAAAAAAIAEgCIAFAAIAFAAQAFAAACAFIAAB+IgDAEQgDACgDAAg");
	this.shape_13.setTransform(-83.3,-8.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgEBEQgFAAgCgEIAAh/IADgDIAFgBIAEAAIAEAAQAGAAABAEIAAB+QAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBABIgEABIgFAAg");
	this.shape_14.setTransform(-93.2,-8.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AACBDIgEAAIgGgBQgDgCAAgEIAAhhQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBgBAAAAQgBgBgFAAIgLgBIgKAAIgFABQgEAAgBgEIgBgGIAAgEIAAgEIACgEQABAAAAgBQAAAAABAAQAAAAABAAQABgBAAAAIBbAAQADAAACADIABAGIAAAFIgBAEIgCAEQAAAAgBABQAAAAAAAAQgBAAgBAAQAAABgBAAIgaAAIgFABQgCABAAAEIAABgQAAABAAAAQAAABAAABQAAAAgBABQAAAAgBABIgDACg");
	this.shape_15.setTransform(-101.6,-8.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgdA/QgOgFgLgKIgBgCIgBgDQAAAAAAgBQAAAAABgBQAAAAAAgBQABgBAAAAIAEgFIAFgDIAEgBQADAAADACIAJAGIALAFQAHADAIAAIAKgBQAFgBAFgCQAFgCADgEQADgEAAgGQAAgFgEgEQgDgDgGgBIgOgDIgPgCIgPgEQgIgCgGgDQgGgEgDgGQgEgHAAgKQAAgKAFgIQAFgHAIgFQAIgFAKgCQAKgDAIAAIAMABIAOADIAMAFQAGAEAEAEIABACIABADQAAAAAAABQAAABgBAAQAAABAAAAQAAABgBAAIgEAEIgFADIgFACIgDgBQgIgGgHgEQgIgDgJAAIgJABIgJADQgEACgDADQgCAEAAAFQAAAHAGAEQAGADAKABIATADQALABAJAEQAKADAGAHQAHAHAAAOQAAALgGAIQgFAJgJAFQgIAGgKACQgLADgJAAQgOAAgOgGg");
	this.shape_16.setTransform(-113.5,-8.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAwBCIgHAAQgDgBgCgDIgHgSIgDgDIgDgBIgsAAIgCAAIgCACIgCABIgBABIgHASIgCACIgEABIgEABIgEAAIgDAAIgEAAIgEgCQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIA2h8QAAgBAAAAQABAAAAgBQABAAAAAAQABgBAAAAIAEgBIAFABQAEAAABADIA0B8IAAABQAAAAAAAAQAAABAAAAQAAABgBAAQAAAAAAAAIgEABIgFABgAgCgSIgBADIgDAHIgEAHIgDAHIgCAFIgBADIABADQAAAAABABQAAAAAAAAQABAAAAAAQAAAAABAAIAZAAIADAAIABgDIgCgGIgEgKIgFgMIgDgGIgDgBIgBAAg");
	this.shape_17.setTransform(-126.2,-8.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AACBDIgEAAIgGgBQgDgCAAgEIAAhhQAAgBAAAAQgBgBAAAAQAAgBAAAAQgBgBAAAAQgBgBgFAAIgLgBIgKAAIgFABQgEAAgBgEIgBgGIAAgEIAAgEIACgEQABAAAAgBQABAAAAAAQABAAAAAAQABgBAAAAIBbAAQADAAACADIABAGIAAAFIgBAEIgCAEQAAAAgBABQAAAAgBAAQAAAAgBAAQAAABgBAAIgaAAIgFABQgCABAAAEIAABgQAAABAAAAQAAABAAABQgBAAAAABQAAAAgBABIgDACg");
	this.shape_18.setTransform(-138.1,-8.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.tastingeventnearyou, new cjs.Rectangle(-145.7,-19.8,261.4,23.3), null);


(lib.savorysides = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgSB+IgZgFIgIAFIgHABIgFgBIgFgDQgIgHgHgUQgHgTAAgSQAAgIAEgFQAEgFAGAAQAMAAALATIAJAPQAHAKANAFQAMAGAOAAQAQAAAJgIQAJgIAAgOQAAgUgngUIgOgGQgmgTgNgPQgNgQAAgXQAAgfAVgUQAWgUAjAAIARABIARADIALgEIAIgCQALAAAMATQALATAAAVQAAAJgEAFQgEAEgGAAQgGAAgFgEQgGgFgHgMQgJgOgKgGQgJgGgOAAQgNAAgJAIQgIAHAAANQAAALAJAJQAIAIAeAPIACACQBEAgAAAnQAAAigaAWQgaAXgnAAg");
	this.shape.setTransform(128.9,-8.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhOBbQgjgjAAg0QAAg4AkgkQAkglA1AAQAvAAAcAbQAbAaAAAtQAAAPgFAFQgEAFgSAAIhcAAQgJAAgEgEQgEgEAAgHQAAgGAEgDQAFgEAHAAIAyAAIAMgCQAEgCAAgFQAAgXgQgQQgPgQgWAAQgdAAgOAZQgOAZAAAkQAAAlAUAbQATAcAdAAQASAAAMgEQANgEALgIIAJgHQAMgKAHAAQAFAAAEADQAEAEAAAFQgBAFgFAJQgHAIgKAJQgVARgTAIQgUAHgXAAQgyAAgjgjg");
	this.shape_1.setTransform(105.8,-8.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhpCSQgdghAAg0QAAg7AhgkQAhglAzAAIARACQAIACAEAGQAEAFAAAGQAAANgQAAIgHgBIgGAAQgbAAgQAWQgQAVAAAmQAAApASAZQARAaAbAAQAZAAAOgOQAOgOAAgbIAAhCIAAhvQAAgRgDgGQgDgHgJgDIgHgCQgPgEAAgJQAAgGAGgFQAGgFASgGIAbgIIAXgDQAIAAAEAFQADAEAAALIAAAMIgDCVIACBlQABAXAEADIARAGQANACAAAJQAAALgjAMIgYAGIgTACQgHAAgDgEQgDgEAAgIIAAgLIAAgFIgBgCIgIAFIgKAIQgPALgNAFQgOAGgPAAQgtAAgcghg");
	this.shape_2.setTransform(79.6,-13.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgqCsQgMgDAAgLQAAgJALgEIAHgCQAGgEADgIQACgIAAgSIAAgQIAAgUIAAgZQAAgmgCgLQgCgLgFgDIgLgEQgPgEAAgJQAAgFAFgEQAEgEAKgFIAlgLIAZgFQAGAAADAFQADAEAAALIAAAOIgBALIgBA9IAAABIgBA8QAAAXACAJQACAKAFADIAJADQANAFAAAKQAAAIgMAEQgMAFggAAQgkAAgLgFgAgdh5QgLgJAAgNQAAgNAMgJQALgLARAAQAOABALAIQAKAJAAAOQAAAMgLAKQgLAJgRAAQgPAAgKgIg");
	this.shape_3.setTransform(57.5,-13.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("Ag7CvQgbgHgRgJQgKgHgGgUQgGgVAAgbQAAgLAEgGQAEgFAIgBQAMAAALAWIAGAKQAQAbASAMQASAMAZAAQAaAAASgPQASgPAAgYQAAghhHggIgHgDQg7gZgTgWQgTgVAAgiQAAgrAggcQAggcAzAAIAcADIAhAHIAKgGIAIgDQAGABAFAEQAEADAFAJQAIAPAFAQQAFAQAAAMQAAAHgEAFQgEAFgHAAQgMAAgNgSIgDgFQgOgSgQgIQgQgJgUAAQgaAAgQANQgPAMAAAXQAAATANANQAMANA0AWIAKAFQArASATARQANALAHARQAHAQAAAUQAAAxgiAbQgjAcg8AAQgdAAgbgFg");
	this.shape_4.setTransform(36.6,-13.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhvCgQgLgKAAgQQAAgMAIgIQAIgJAMAAIALACIAHAFIAHAJQAGAKAFAAQAMAAANgSQAMgSAAgTQABgVgSgmIgCgGIgmhUIgXgvQgEgIgOgGQgJgEgDgDQgCgDAAgGQAAgKAMgEQANgFAjAAQAkAAAMAEQAMAEgBAKIgBAHIgFAFIgJAEQgIAEgBAEIAGASIATAwIATAuQAGALADAAQADAAAFgLIARgmIARgwQAGgRAAgGQAAgHgOgIQgNgIAAgGQgBgIAMgEQALgEAbAAQAdAAAKAEQALAEAAAKQAAAJgOADIgKAEQgOAHgPApIgHATIgfBNQgoBkgZAeQgaAfgjAAQgRAAgMgKg");
	this.shape_5.setTransform(-2.6,-3.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhJB4QgLgEAAgLQAAgIALgEIAHgDQAGgEADgIQACgIAAgSIAAgQIgBgUIAAgOQABgsgCgNQgCgOgGgDIgKgEQgPgEAAgJQAAgFAFgEQAEgEAKgFIAhgKIAVgFQAMAAAEAhIABAFIACABQALgTAOgLQANgKAOAAQARAAAKAKQAKAKAAARQAAARgHAKQgJAJgNAAIgMgCIgKgHIgGgKQgDgGgCAAQgRAAgHAXQgFAXAABJQAAAVACALQADAKAGADIAKADQAOAFAAAKQAAAJgNAEQgNAEghAAQglAAgMgEg");
	this.shape_6.setTransform(-23.5,-8.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhXBaQgjgjAAg2QAAg2AlgkQAkgkA1AAQA0AAAhAiQAiAiAAA1QAAA3gkAlQgkAmg0AAQg0AAgigkgAgthHQgPATAAAhQAAAvAUAgQAVAgAcAAQAXAAAPgUQAPgUAAggQAAgvgVggQgUgggcAAQgYAAgOAUg");
	this.shape_7.setTransform(-46.9,-8.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgZBlQgOgXgihQIgOgjQgRgugLgGIgHgDQgOgFAAgJQAAgKAMgEQAMgEAnAAQAhAAAMAEQAMAEAAAKIgCAIIgEAEIgIADQgKAFAAAFIAFATIATAvIATAuQAGALADAAQADAAAFgGIALgWIAag8QAIgXAAgJIgCgIIgFgGIgHgDQgLgEAAgIQAAgJALgEQALgEAeAAQAZAAAKAEQAKAEAAAJQAAAKgMAEIgIADQgMAFgUAwIgGAPIgKAWQg3B9gPAAQgLAAgNgYg");
	this.shape_8.setTransform(-72.9,-8.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AArByIgNgNIgKAFQgeAUgeAAQgjAAgWgUQgVgVAAghQAAgnAcgVQAcgVAyAAQAMAAAGADQAGAEAAAKQAAANgRgBQgXABgPAMQgOALAAAUQAAAUAMALQANAMAVAAQAXAAAKgKQAKgLAAgZIAAhcQAAgVgJgLQgJgMgRAAQgLAAgLAFQgKAFgJAMIgFAGQgPASgQABQgKgBgGgGQgFgGAAgLQAAgWAcgPQAcgQAsAAQAaAAATAHQATAHALANQAHAKADAPQADAOAAAjIAABNQAAAOACAGQADAHAFABIAHACQAPAFAAAIQAAALgQAKQgQAJgWAAQgKAAgMgMg");
	this.shape_9.setTransform(-98.1,-8.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag7CvQgbgHgRgJQgKgHgGgUQgGgVAAgbQAAgLAEgGQAEgFAIgBQAMAAALAWIAGAKQAQAbASAMQASAMAZAAQAaAAASgPQASgPAAgYQAAghhHggIgHgDQg7gZgTgWQgTgVAAgiQAAgrAggcQAggcAzAAIAcADIAhAHIAKgGIAIgDQAGABAFAEQAEADAFAJQAIAPAFAQQAFAQAAAMQAAAHgEAFQgEAFgHAAQgMAAgNgSIgDgFQgOgSgQgIQgQgJgUAAQgaAAgQANQgPAMAAAXQAAATANANQAMANA0AWIAKAFQArASATARQANALAHARQAHAQAAAUQAAAxgiAbQgjAcg8AAQgdAAgbgFg");
	this.shape_10.setTransform(-125.4,-13.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.savorysides, new cjs.Rectangle(-141.5,-44.7,283,61.4), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.greyrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(1,1,1).p("EhK2gSvMCVtAAAMAAAAlfMiVtAAAg");
	this.shape.setTransform(0,0,1.011,1.037);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greyrectangle, new cjs.Rectangle(-485.5,-125.5,971,251), null);


(lib.foryourfeast = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgZBKQgFgDAAgDIAFgKIAFgHIAOgaQAFgNAAgEIgCgGIgIgFQgMgFgGgIQgGgJAAgNQAAgQAKgLQAKgKAPAAQAPAAALAOQAKAOAAAWQAAAQgGARQgGARgQAaIgMATQgGAGgEAAQgHAAgEgCg");
	this.shape.setTransform(155.6,4.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgMCRQgNgEgIgHQgIgJgEgMQgEgOAAglIAAiAIgVAAIgIgCIgCgGIAAgGQAAgIAagVIAKgJIAJgIQAZgWAJAAIAHACQACACABAEIAAAtIA2AAQAFAAADADQACABAAAIIAAAFQAAAGgCADQgDADgFAAIgzAAIgDACIgBAFIAAB4QgBAfAGAIQAFAHAOABQAIgBAMgDIARgEQAFAAADADQADADABAFQgBAOgTAMQgWAMgaAAQgOAAgLgEg");
	this.shape_1.setTransform(139.9,-10.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgSB+IgZgFIgIAFIgHABIgFgBIgFgDQgIgHgHgUQgHgTAAgSQAAgIAEgFQAEgFAGAAQAMAAALATIAJAPQAHAKANAFQAMAGAOAAQAQAAAJgIQAJgIAAgOQAAgUgngUIgOgGQgmgTgNgPQgNgQAAgXQAAgfAVgUQAWgUAjAAIARABIARADIALgEIAIgCQALAAAMATQALATAAAVQAAAJgEAFQgEAEgGAAQgGAAgFgEQgGgFgHgMQgJgOgKgGQgJgGgOAAQgNAAgJAIQgIAHAAANQAAALAJAJQAIAIAeAPIACACQBEAgAAAnQAAAigaAWQgaAXgnAAg");
	this.shape_2.setTransform(120.7,-8.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AArByIgNgNIgKAFQgeAUgeAAQgjAAgWgUQgVgVAAghQAAgnAcgVQAcgVAyAAQAMAAAGADQAGAEAAAKQAAANgRgBQgXABgPAMQgOALAAAUQAAAUAMALQANAMAVAAQAXAAAKgKQAKgLAAgZIAAhcQAAgVgJgLQgJgMgRAAQgLAAgLAFQgKAFgJAMIgFAGQgPASgQABQgKgBgGgGQgFgGAAgLQAAgWAcgPQAcgQAsAAQAaAAATAHQATAHALANQAHAKADAPQADAOAAAjIAABNQAAAOACAGQADAHAFABIAHACQAPAFAAAIQAAALgQAKQgQAJgWAAQgKAAgMgMg");
	this.shape_3.setTransform(97.8,-8.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhOBbQgjgjABg0QgBg4AkgkQAkglA2AAQAuAAAcAbQAbAaAAAtQAAAPgFAFQgEAFgSAAIhcAAQgIAAgFgEQgEgEAAgHQAAgGAEgDQAFgEAIAAIAxAAIANgCQADgCAAgFQAAgXgQgQQgPgQgWAAQgdAAgOAZQgOAZAAAkQAAAlAUAbQASAcAeAAQASAAANgEQAMgEALgIIAJgHQAMgKAHAAQAFAAAEADQADAEABAFQAAAFgHAJQgFAIgLAJQgVARgTAIQgUAHgXAAQgyAAgjgjg");
	this.shape_4.setTransform(71.8,-8.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ah6CtQgNgFAAgLQAAgJAMgFQANgFADgEQADgEACgkIACheIgChZQgDglgCgEQgDgDgMgGQgNgFAAgLQAAgJALgDQALgEApAAICUAAIAXgDIANgCIAGABIAEAEQAFAKAFAQQAEARAAALQAAALgEAGQgEAGgHAAQgIAAgKgRIgIgLQgFgIgLgDQgKgFgQAAIgiAAQgWABgMACQgMADgEAFQgEAFgCAQIgCAvIAAATQAAAMACACQACADAHAAIAnAAQATAAAIgGQAHgFACgPIABgFQAEgYANAAQAKAAAEAMQAEAOAAAuQAAAugEAMQgEANgKABQgNAAgEgaIgBgEQgCgQgHgFQgIgGgTABIgnAAQgGgBgDAFQgCAEAAAPIAAASIACBFQABAOAFADIAKAFQAPAGAAAKQAAAKgNAFQgOAEglAAQgnAAgNgEg");
	this.shape_5.setTransform(44.8,-13.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhJB4QgLgEAAgLQAAgIALgEIAHgDQAGgEADgIQACgIAAgSIAAgQIgBgUIAAgOQAAgsgBgNQgCgOgFgDIgLgEQgPgEAAgJQAAgFAFgEQAEgEAKgFIAhgKIAVgFQANAAADAhIABAFIABABQAMgTAOgLQANgKAOAAQARAAAKAKQAKAKAAARQAAARgHAKQgIAJgOAAIgMgCIgKgHIgGgKQgDgGgCAAQgRAAgGAXQgGAXAABJQAAAVACALQADAKAGADIAKADQAOAFAAAKQAAAJgNAEQgOAEggAAQglAAgMgEg");
	this.shape_6.setTransform(7.9,-8.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AA0B7QgDgEAAgIIAAgRIAAgCIgBAAQgDABgGAFIgDAEQgLAMgPAFQgOAHgSgBQgSABgQgIQgQgGgKgNQgMgOgEgTQgFgUAAgyIAAgRIAAgRIAAgGQAAgUgCgFQgDgGgJgDIgKgDQgNgDAAgJQAAgGAFgEQAEgEARgGIAhgIIAagEQAGAAADAFQADAFAAAKIAAAKIgDBaQAAAwALATQAKATAYAAQAbAAAMgZQAMgXAAg7IAAgTQAAgSgCgGQgDgGgJgDIgJgDQgOgDAAgJQAAgFAFgEQAFgFARgGIAggIIAZgEQAIAAADAFQACAEAAALIAAAOIgDBiIABAqIABAPQACAKAMAFIAFABQANAFAAAJQAAAFgEAEQgEADgLAFIgiALQgRAEgIAAQgHAAgEgDg");
	this.shape_7.setTransform(-16.5,-8.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhXBaQgjgjAAg2QAAg2AlgkQAkgkA1AAQA0AAAhAiQAiAiAAA1QAAA3gkAlQgkAmg0AAQg0AAgigkgAgthHQgPATAAAhQAAAvAUAgQAVAgAcAAQAXAAAPgUQAPgUAAggQAAgvgVggQgUgggcAAQgYAAgOAUg");
	this.shape_8.setTransform(-44.2,-8.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgyCqQgOgEAAgKQAAgKAPgGIALgGQAHgGABhiIABgWIgdgvIgthIQgPgUgIgFIgMgGQgQgEAAgKQAAgKAMgEQALgDAvAAQAvAAALADQAMAEAAAKQAAAJgTAIIgBAAIgIAEIgDAIQAAAFALASIAwBLIAqg/QANgWAAgHQAAgGgDgEQgFgFgLgEQgJgDgCgEQgDgDgBgGQAAgKALgEQAJgDAoAAQAnAAALADQAJAEABAKQAAAKgOAFIgSAKQgLAIgXAiQgXAjgjA8IAAArQACBRAGAEIAKAGQAQAGAAAKQAAAKgOAEQgNAFgmAAQglAAgNgFg");
	this.shape_9.setTransform(-73.3,-13.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhIB4QgMgEAAgLQAAgIAMgEIAGgDQAGgEACgIQADgIAAgSIAAgQIgBgUIAAgOQAAgsgBgNQgCgOgGgDIgLgEQgOgEAAgJQAAgFAEgEQAFgEALgFIAggKIAWgFQALAAAFAhIAAAFIACABQAMgTANgLQAOgKAOAAQAQAAAKAKQAKAKAAARQAAARgIAKQgIAJgNAAIgNgCIgJgHIgGgKQgCgGgDAAQgRAAgHAXQgFAXAABJQAAAVACALQADAKAGADIAKADQAPAFAAAKQAAAJgOAEQgNAEghAAQglAAgLgEg");
	this.shape_10.setTransform(-110.9,-8.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhXBaQgjgjAAg2QAAg2AlgkQAkgkA1AAQA0AAAhAiQAiAiAAA1QAAA3gkAlQgkAmg0AAQg0AAgigkgAgthHQgPATAAAhQAAAvAUAgQAVAgAcAAQAXAAAPgUQAPgUAAggQAAgvgVggQgUgggcAAQgYAAgOAUg");
	this.shape_11.setTransform(-134.3,-8.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AhDCtQgMgEAAgJQAAgIALgEIAGgDQAGgDADgIQACgIAAgUIAAgYIAAh0IgbAAQgGABgCgDQgCgDAAgGIAAgGQAAgGACgDQADgCAFAAIAaAAIgDgTIgBgRQAAgmAXgTQAWgVAnAAQAbAAARANQARALAAAUQAAALgGAGQgGAGgMAAQgHAAgGgEQgHgDgEgHIgEgIQgJgSgOAAQgJABgFAFQgGAHAAAJIAGAbQAEAVABARIAjAAQAGgBACADQACACAAAHIAAAGQAAAGgCADQgCADgGgBIgjAAIAAB8QAAAfACAJQACAKAFADIAJADQAPAFAAAKQAAAIgMAEQgMAEgiAAQgkAAgLgEg");
	this.shape_12.setTransform(-152.7,-14);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.foryourfeast, new cjs.Rectangle(-163.8,-44.7,327.6,61.4), null);


(lib.Path = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("Ap8XiQklh8jijiQjjjih7kmQiBkwAAlMQAAlMCBkvQB7kmDjjiQDijiElh8QExiBFLAAQFMAAExCBQElB8DiDiQDiDiB9EmQCAEvAAFMQAAFMiAEwQh9EmjiDiQjiDiklB8QkxCBlMAAQlLAAkxiBg");
	this.shape.setTransform(163.5,163.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path, new cjs.Rectangle(0,0,327,327), null);


(lib.findanevent = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgVA4QgKgFgGgIIAMgLQAEAHAHADQAGAEAIAAIAHgBQAEgBAEgDQADgCACgEQACgDAAgFQAAgGgCgDQgCgDgEgDQgEgDgFgBIgJgEIgLgDQgFgCgEgEQgEgDgDgFQgCgGAAgHQAAgJADgGQAEgGAFgEQAGgEAHgCIANgCIAJABIAJADQAJADAFAHIgLAKQgEgEgFgDQgGgDgHAAIgHABIgHADIgFAGQgCADAAAFQAAAEABAEIAFAFIAIAEIAIADIAMAEQAFACAFADQAFAEADAFQADAFAAAJQAAAJgDAGQgDAHgGAEQgFAEgHACQgIACgGAAQgLAAgKgDg");
	this.shape.setTransform(54.7,18.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AggA5IAAhxIAQAAIAABjIAxAAIAAAOg");
	this.shape_1.setTransform(46.8,18.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgHA5IAAhxIAPAAIAABxg");
	this.shape_2.setTransform(40,18.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAmA5IgLgcIg1AAIgMAcIgRAAIAxhxIAOAAIAwBxgAAVAPIgVg0IgVA0IAqAAg");
	this.shape_3.setTransform(32.2,18.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgHA5IAAhjIgkAAIAAgOIBXAAIAAAOIgkAAIAABjg");
	this.shape_4.setTransform(21.9,18.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgkA5IAAhxIBHAAIAAAOIg4AAIAAAiIA0AAIAAANIg0AAIAAAmIA6AAIAAAOg");
	this.shape_5.setTransform(12.9,18.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgxA5IAAhxIAmAAQALAAALAEQALADAIAHQAJAHAGAKIADAMQACAHAAAGQAAAHgCAHIgDALIgHAKIgIAIQgIAHgLADQgOAEgIAAgAghArIATAAQALAAAHgDQAJgDAHgFQAGgGADgIIADgIIABgKIgBgJIgDgIQgDgIgGgGQgHgFgJgDQgHgDgLAAIgTAAg");
	this.shape_6.setTransform(2,18.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgHA5IAAhjIgkAAIAAgOIBXAAIAAAOIgkAAIAABjg");
	this.shape_7.setTransform(-12.9,18.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAcA5Ig7hcIgBAAIAABcIgPAAIAAhxIAVAAIA5BaIABAAIAAhaIAQAAIAABxg");
	this.shape_8.setTransform(-23.6,18.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AglA5IAAhxIBIAAIAAAOIg4AAIAAAiIA1AAIAAANIg1AAIAAAmIA7AAIAAAOg");
	this.shape_9.setTransform(-34.3,18.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgGA5IgthxIASAAIAhBcIABAAIAihcIARAAIgtBxg");
	this.shape_10.setTransform(-44.6,18.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgkA5IAAhxIBHAAIAAAOIg4AAIAAAiIA0AAIAAANIg0AAIAAAmIA6AAIAAAOg");
	this.shape_11.setTransform(-54.1,18.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.findanevent, new cjs.Rectangle(-61.4,6.2,122.9,23.7), null);


(lib.deliciousdessertsbillboard = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgSB+IgZgFIgIAFIgHABIgFgBIgFgDQgIgHgHgUQgHgTAAgSQAAgIAEgFQAEgFAGAAQAMAAALATIAJAPQAHAKANAFQAMAGAOAAQAQAAAJgIQAJgIAAgOQAAgUgngUIgOgGQgmgTgNgPQgNgQAAgXQAAgfAVgUQAWgUAjAAIARABIARADIALgEIAIgCQALAAAMATQALATAAAVQAAAJgEAFQgEAEgGAAQgGAAgFgEQgGgFgHgMQgJgOgKgGQgJgGgOAAQgNAAgJAIQgIAHAAANQAAALAJAJQAIAIAeAPIACACQBEAgAAAnQAAAigaAWQgaAXgnAAg");
	this.shape.setTransform(191.9,-8.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgMCRQgMgEgJgHQgJgJgDgMQgDgOAAglIAAiAIgXAAIgGgCIgDgGIAAgGQAAgIAZgVIAKgJIAKgIQAZgWAJAAIAHACQACACAAAEIAAAtIA2AAQAHAAACADQACABAAAIIAAAFQAAAGgDADQgCADgGAAIgxAAIgEACIgCAFIAAB4QABAfAFAIQAFAHAOABQAIgBAMgDIARgEQAEAAAEADQAEADgBAFQABAOgVAMQgUAMgaAAQgOAAgMgEg");
	this.shape_1.setTransform(173.2,-10.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhJB4QgLgEAAgLQAAgIALgEIAHgDQAGgEACgIQADgIAAgSIAAgQIgBgUIAAgOQAAgsgBgNQgCgOgGgDIgLgEQgOgEAAgJQAAgFAEgEQAFgEALgFIAggKIAWgFQAMAAADAhIABAFIACABQAMgTANgLQAOgKAOAAQAQAAAKAKQAKAKAAARQAAARgHAKQgJAJgNAAIgNgCIgJgHIgGgKQgCgGgDAAQgRAAgHAXQgFAXAABJQAAAVACALQADAKAGADIAKADQAPAFAAAKQAAAJgOAEQgNAEghAAQgkAAgNgEg");
	this.shape_2.setTransform(155.8,-8.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhOBbQgjgjAAg0QAAg4AkgkQAkglA1AAQAvAAAcAbQAbAaAAAtQAAAPgFAFQgEAFgSAAIhcAAQgJAAgEgEQgEgEAAgHQAAgGAEgDQAFgEAHAAIAyAAIAMgCQAEgCAAgFQAAgXgQgQQgPgQgWAAQgdAAgOAZQgOAZAAAkQAAAlAUAbQATAcAdAAQASAAAMgEQANgEALgIIAJgHQAMgKAHAAQAFAAAEADQAEAEAAAFQgBAFgFAJQgHAIgKAJQgVARgTAIQgUAHgXAAQgyAAgjgjg");
	this.shape_3.setTransform(133.3,-8.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgSB+IgZgFIgIAFIgHABIgFgBIgFgDQgIgHgHgUQgHgTAAgSQAAgIAEgFQAEgFAGAAQAMAAALATIAJAPQAHAKANAFQAMAGAOAAQAQAAAJgIQAJgIAAgOQAAgUgngUIgOgGQgmgTgNgPQgNgQAAgXQAAgfAVgUQAWgUAjAAIARABIARADIALgEIAIgCQALAAAMATQALATAAAVQAAAJgEAFQgEAEgGAAQgGAAgFgEQgGgFgHgMQgJgOgKgGQgJgGgOAAQgNAAgJAIQgIAHAAANQAAALAJAJQAIAIAeAPIACACQBEAgAAAnQAAAigaAWQgaAXgnAAg");
	this.shape_4.setTransform(110,-8.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgSB+IgZgFIgIAFIgHABIgFgBIgFgDQgIgHgHgUQgHgTAAgSQAAgIAEgFQAEgFAGAAQAMAAALATIAJAPQAHAKANAFQAMAGAOAAQAQAAAJgIQAJgIAAgOQAAgUgngUIgOgGQgmgTgNgPQgNgQAAgXQAAgfAVgUQAWgUAjAAIARABIARADIALgEIAIgCQALAAAMATQALATAAAVQAAAJgEAFQgEAEgGAAQgGAAgFgEQgGgFgHgMQgJgOgKgGQgJgGgOAAQgNAAgJAIQgIAHAAANQAAALAJAJQAIAIAeAPIACACQBEAgAAAnQAAAigaAWQgaAXgnAAg");
	this.shape_5.setTransform(89.1,-8.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhOBbQgigjAAg0QAAg4AjgkQAkglA2AAQAuAAAbAbQAcAaAAAtQAAAPgEAFQgFAFgSAAIhcAAQgIAAgFgEQgEgEAAgHQAAgGAEgDQAFgEAIAAIAxAAIANgCQADgCgBgFQAAgXgPgQQgQgQgVAAQgdAAgOAZQgOAZAAAkQAAAlAUAbQASAcAeAAQASAAANgEQAMgEALgIIAJgHQANgKAGAAQAFAAAEADQADAEABAFQAAAFgHAJQgFAIgLAJQgVARgTAIQgUAHgXAAQgyAAgjgjg");
	this.shape_6.setTransform(66.1,-8.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag0CuIgegBIgUABIgUAAQgeAAgJgEQgJgEAAgKQAAgJAMgFQANgFADgEQADgFACgkIAChdIgChZQgDglgCgFQgDgDgMgFQgNgGAAgJQAAgKAKgEQAKgEAdAAIAVABIAYAAIAggBIAcgBQBZAAAxAvQAxAuAABVQAABUgyAsQgyArhgAAgAg1iJQgLAEgCAIQgEAJgBAcIgCBJIACBcQACAmADAHQACAIAQAFQAQAFAWAAQA3AAAcghQAbgiAAhDQAAhHgfgmQgggmg7AAQgUAAgLAEg");
	this.shape_7.setTransform(34.5,-13.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgSB+IgZgFIgIAFIgHABIgFgBIgFgDQgIgHgHgUQgHgTAAgSQAAgIAEgFQAEgFAGAAQAMAAALATIAJAPQAHAKANAFQAMAGAOAAQAQAAAJgIQAJgIAAgOQAAgUgngUIgOgGQgmgTgNgPQgNgQAAgXQAAgfAVgUQAWgUAjAAIARABIARADIALgEIAIgCQALAAAMATQALATAAAVQAAAJgEAFQgEAEgGAAQgGAAgFgEQgGgFgHgMQgJgOgKgGQgJgGgOAAQgNAAgJAIQgIAHAAANQAAALAJAJQAIAIAeAPIACACQBEAgAAAnQAAAigaAWQgaAXgnAAg");
	this.shape_8.setTransform(-7.8,-8.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AA0B7QgDgEAAgIIAAgRIAAgCIgBAAQgDABgGAFIgDAEQgLAMgPAFQgOAHgSgBQgSABgQgIQgQgGgKgNQgMgOgEgTQgFgUAAgyIAAgRIAAgRIAAgGQAAgUgCgFQgDgGgJgDIgKgDQgNgDAAgJQAAgGAFgEQAEgEARgGIAhgIIAagEQAGAAADAFQADAFAAAKIAAAKIgDBaQAAAwALATQAKATAYAAQAbAAAMgZQAMgXAAg7IAAgTQAAgSgCgGQgDgGgJgDIgJgDQgOgDAAgJQAAgFAFgEQAFgFARgGIAggIIAZgEQAIAAADAFQACAEAAALIAAAOIgDBiIABAqIABAPQACAKAMAFIAFABQANAFAAAJQAAAFgEAEQgEADgLAFIgiALQgRAEgIAAQgHAAgEgDg");
	this.shape_9.setTransform(-32.7,-8.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhXBaQgjgjAAg2QAAg2AlgkQAkgkA1AAQA0AAAhAiQAiAiAAA1QAAA3gkAlQgkAmg0AAQg0AAgigkgAgthHQgPATAAAhQAAAvAUAgQAVAgAcAAQAXAAAPgUQAPgUAAggQAAgvgVggQgUgggcAAQgYAAgOAUg");
	this.shape_10.setTransform(-60.4,-8.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgqCsQgMgDAAgLQAAgJALgEIAHgCQAGgEADgIQACgIAAgSIAAgQIAAgUIAAgZQAAgmgCgLQgCgLgFgDIgLgEQgPgEAAgJQAAgFAFgEQAFgEAJgFIAlgLIAZgFQAGAAADAFQADAEAAALIAAAOIAAALIgCA9IAAABIgBA8QAAAXACAJQACAKAFADIAJADQANAFAAAKQAAAIgMAEQgMAFgfAAQgkAAgMgFgAgdh5QgLgJABgNQgBgNAMgJQAMgLAQAAQAPABAKAIQAKAJAAAOQAAAMgLAKQgMAJgPAAQgQAAgKgIg");
	this.shape_11.setTransform(-80.9,-13.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AhMBbQgigjAAg0QAAg3AkglQAkglA2AAQAnAAAcAVQAcAVAAAbQAAAMgHAHQgIAHgMAAQgNAAgHgGQgHgGgJgUQgHgRgKgHQgJgHgPAAQgbAAgPAVQgQAVAAAlQAAAqAWAbQAWAcAiAAQAMAAALgEQALgDAJgGIAJgHQANgKAHAAQAGAAADADQACACAAAGQAAAGgFAIQgFAJgIAHQgTAQgUAIQgVAIgYAAQgyAAgigjg");
	this.shape_12.setTransform(-100,-8.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgqCsQgMgDAAgLQAAgJALgEIAHgCQAGgEACgIQADgIAAgSIAAgQIAAgUIAAgZQAAgmgCgLQgCgLgFgDIgLgEQgPgEAAgJQAAgFAFgEQAEgEALgFIAkgLIAZgFQAGAAAEAFQACAEAAALIAAAOIAAALIgCA9IAAABIgBA8QAAAXACAJQACAKAGADIAJADQAMAFAAAKQAAAIgMAEQgMAFgfAAQglAAgLgFgAgdh5QgKgJAAgNQAAgNALgJQALgLAQAAQAPABALAIQAKAJAAAOQAAAMgLAKQgLAJgQAAQgQAAgKgIg");
	this.shape_13.setTransform(-119.4,-13.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgoCtQgMgDAAgLQAAgHAKgFIAMgHQAFgDABgQIACgvIAAgmIAAgtIAAgSQAAg9gCgSQgDgRgFgDIgPgGQgPgDAAgJQAAgGAFgEQAFgEAQgGIAhgJIAYgEQAIABADAEQACAFAAALIAAATQgDBVAABYIABBRQACASAEAEIANAHQAMAFAAAKQAAAIgMAEQgMAFggAAQgjAAgMgFg");
	this.shape_14.setTransform(-133.3,-14);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AhOBbQgigjgBg0QABg4AjgkQAkglA1AAQAvAAAbAbQAbAaAAAtQAAAPgDAFQgFAFgSAAIhcAAQgIAAgEgEQgFgEAAgHQAAgGAFgDQADgEAJAAIAyAAIAMgCQACgCAAgFQAAgXgPgQQgQgQgVAAQgdAAgOAZQgOAZAAAkQAAAlATAbQAUAcAeAAQARAAAMgEQANgEAMgIIAIgHQANgKAGAAQAGAAADADQADAEAAAFQABAFgHAJQgFAIgLAJQgVARgUAIQgTAHgXAAQgyAAgjgjg");
	this.shape_15.setTransform(-152.4,-8.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("Ag0CuIgegBIgUABIgUAAQgeAAgJgEQgJgEAAgKQAAgJAMgFQANgFADgEQADgFACgkIAChdIgChZQgDglgCgFQgDgDgMgFQgNgGAAgJQAAgKAKgEQAKgEAdAAIAVABIAYAAIAggBIAcgBQBZAAAxAvQAxAuAABVQAABUgyAsQgyArhgAAgAg1iJQgLAEgCAIQgEAJgBAcIgCBJIACBcQACAmADAHQACAIAQAFQAQAFAWAAQA3AAAcghQAbgiAAhDQAAhHgfgmQgggmg7AAQgUAAgLAEg");
	this.shape_16.setTransform(-184,-13.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.deliciousdessertsbillboard, new cjs.Rectangle(-204.5,-44.7,409,61.4), null);


(lib.date = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgIAJQgEgEAAgFQAAgFAEgDQADgEAFAAQAFAAAEAEQAEADAAAFQAAAFgEAEQgEAEgFAAQgFAAgDgEg");
	this.shape.setTransform(-213.3,36.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAsBDIgGgBQgDgCAAgEIAAg7IgCgDIgDgBQAAAAgBABQAAAAgBAAQAAAAgBABQAAAAAAABIgWAhQgCAEgDAAIgEgBIgDgDIgSgiQgBAAAAAAQAAgBgBAAQAAAAgBAAQAAgBgBAAQAAAAgBABQAAAAgBAAQAAAAAAAAQgBABAAAAIgBADIAAA6QgCAFgEABIgIABIgEAAIgDgCIgDgCIgBgDIAAh3QACgFAEAAIAHgBIAEABQADABACACIAeA0QADAFAEAAIADgBIADgEIAggzQADgGAHAAIAGABQACABABADIAAB5QAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAIgDACIgGABg");
	this.shape_1.setTransform(-223.4,30.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgIAJQgEgEAAgFQAAgFAEgDQADgEAFAAQAFAAAEAEQAEADAAAFQAAAFgEAEQgEAEgFAAQgFAAgDgEg");
	this.shape_2.setTransform(-233.6,36.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AguBDQgGAAgCgFIAAh8QAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAIAEgBIA5AAQAJAAAIADQAIADAHAFQAGAGAEAHQAEAHAAAKIgBAHIgCAGQgEAMgJAGQgJAFgLADQgKABgLAAIgWAAIgCABIgCABIgCAEIAAApIgDADIgEABIgFABgAgcgpQgCADAAADIAAAVQAAABAAABQAAAAABABQAAAAAAABQAAAAABABQAAAAABAAQAAABABAAQAAAAABAAQABAAAAAAIAhAAIAIgBIAGgDIAFgGQACgEAAgEQAAgDgCgEIgEgFIgHgEIgHgBIghAAQgDAAgCACg");
	this.shape_3.setTransform(-242.3,30.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AALBEQgCgBgBgDIAAgUQAAgEgCgCQgCgCgDAAIgrAAIgFgBQgDgCAAgDIACgFIAnhZQABgCADgBIAFgCIADABIAEACIADADIABAEIgCAGIgEALIgGAOIgGAPIgGAMIgDAGIAAACIgBACQAAAAAAAAQAAABABAAQAAABAAAAQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAQAAAAABAAIAFABIAGgBIAFgCQADgBAAgDIAAgVQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAIAEgCIAFAAIADAAIADAAIADABIADACIABACIAAAVIABAEQABACAEAAIAJAAQAEACABAEIAAAIQAAAFgCACIgFACIgGAAQgDgBgCADIgCACIAAAEIAAANQABAFgBADQgBACgDABIgKACg");
	this.shape_4.setTransform(-260.6,30.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgQALQgBgBAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAIgBgCIgBgFIAAgCIAAgDIABgDIACgCIACgBIAhAAIAEABIACACIABADIAAADIAAAFQgBACgEADIgCABg");
	this.shape_5.setTransform(-269.2,30.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgrBDQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAgBAAQgBgCAAgDIAAgFIAAgGIAAgGIADgEIA6gtIAJgJQACgFAAgGQAAgFgBgEQgDgEgEgCIgIgEIgIgCQgHAAgFADIgJAGIgHAGQgCADgDAAIgFgBIgEgDIgEgEQAAAAgBgBQAAAAAAAAQAAgBAAAAQgBgBAAAAIACgEQAEgGAGgFQAFgEAGgDQANgFANAAQAJAAAJADQAJACAGAFQAHAGAEAHQAEAIAAAKQAAAMgHAJQgGAIgJAHIgiAaIgCACIAAACQAAABAAABQAAAAABABQAAAAABABQAAAAABAAIAyAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAABIACADIABAEIAAAEIgBAGQgBADgEAAg");
	this.shape_6.setTransform(-278.1,30.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAKBCIgFgBIgEgBQgBgBAAAAQAAgBAAAAQAAAAAAgBQAAgBAAAAIAAhTIgBgCQgBgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAQgEAAgDgEQgDgEAAgEIACgFQABgEACgBIAEgCIAHgEIAHgFIAHgEIAGgDIAEgCQAAAAABAAQAAAAABABQAAAAABAAQABABAAAAQABABAAAAQABABAAAAQAAABABAAQAAABAAAAIAAB3QAAADgEABIgGACg");
	this.shape_7.setTransform(-288.1,30.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAsBDIgGgBQgDgCAAgEIAAg7IgCgDIgDgBQAAAAgBABQAAAAgBAAQAAAAgBABQAAAAAAABIgWAhQgCAEgDAAIgEgBIgDgDIgSgiQgBAAAAAAQAAgBgBAAQAAAAgBAAQAAgBgBAAQAAAAgBABQAAAAgBAAQAAAAAAAAQgBABAAAAIgBADIAAA6QgCAFgEABIgIABIgEAAIgDgCIgDgCIgBgDIAAh3QACgFAEAAIAHgBIAEABQADABACACIAeA0QADAFAEAAIADgBIADgEIAggzQADgGAHAAIAGABQACABABADIAAB5QAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAIgDACIgGABg");
	this.shape_8.setTransform(-303.5,30.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgNBDIgOgEQgGgCgGgEIgKgIQgKgKgFgMQgDgGgBgHQgCgHAAgHIACgNQABgHADgGQAFgNAKgJIAKgIIAMgHIAOgEIANgBIAOABIAOAEQAMAGAKAJQAKAJAFANQAGAMAAAOQAAAHgCAHIgEANQgFAMgKAKQgKAJgMAFIgOAEQgHACgHAAQgGAAgHgCgAgQgpQgIADgHAGQgGAHgEAIQgDAIAAAJQAAAJADAJQAEAIAGAGQAHAGAIAEQAIADAIAAQAJAAAIgDQAIgEAGgGQAHgGADgIQAEgJAAgJQAAgJgEgIQgDgIgHgHQgGgGgIgDQgIgEgJAAQgIAAgIAEg");
	this.shape_9.setTransform(-318.7,30.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAhBDIgDgBIgDgBIgBgBIgXgkIgDgEQgDgBgDAAIgRAAIgFABQgCACAAADIABAhQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAIgEACIgFAAIgFAAQgEAAgCgCQgCgBAAgEIAAh5QAAgBAAAAQABgBAAAAQAAgBAAAAQABAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAQABAAAAAAIA4AAQAKAAAIADQAJADAGAGQAGAGAEAIQAEAIAAALQAAALgFAHQgEAGgFAEIgJAHQgEADAAADIAAADIAFAHIAIALIAHAKIADAHQAAAAAAABQgBAAAAABQAAAAAAABQgBAAAAABIgEADIgFACIgFAAgAgbgqQgDACAAAEIAAAdQAAAEADACQADABADAAIAbAAQAFAAAEgBIAIgEQAEgCACgEQABgFAAgFQAAgLgHgGIgIgEQgEgBgFAAIgbAAIgGABg");
	this.shape_10.setTransform(-332.7,30.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgnBDIgEAAQgGAAgCgFIAAh6QAAAAAAgBQAAgBABAAQAAgBAAAAQABgBAAAAQABgBAAAAQABgBAAAAQABAAABAAQAAAAABAAIBaAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAABAAIACAEIAAAEIABAEQAAADgCADQgBADgDABIhCAAQAAAAgBAAQgBAAAAABQgBAAAAAAQgBABAAAAQgBABAAAAQAAABgBAAQAAABAAABQAAAAAAABIAAAQQAAABAAABQAAAAAAABQAAAAABABQAAAAAAABQABAAAAAAQABABAAAAQABAAABAAQAAAAABAAIAqAAQABAAAAAAQABAAAAABQABAAAAAAQAAABABAAIABAFIABAFIAAADIgCAFQgBADgDAAIgqAAIgCAAIgCACIgCACIgBACIAAAvQAAABAAAAQgBABAAAAQAAABgBAAQAAABgBAAIgEABg");
	this.shape_11.setTransform(-344.6,30.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgrBDQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAgBAAQgCgCAAgDIAAgFIAAgGIABgGIADgEIA6gtIAJgJQACgFAAgGQAAgFgCgEQgCgEgEgCIgIgEIgIgCQgIAAgFADIgIAGIgHAGQgDADgCAAIgFgBIgEgDIgEgEQAAAAgBgBQAAAAAAAAQAAgBAAAAQgBgBAAAAIACgEQAEgGAGgFQAFgEAGgDQAMgFAOAAQAJAAAJADQAJACAGAFQAHAGAEAHQAEAIAAAKQAAAMgHAJQgGAIgJAHIgiAaIgCACIAAACQAAABAAABQAAAAABABQAAAAABABQAAAAABAAIAyAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAABIACADIABAEIAAAEIgBAGQgBADgEAAg");
	this.shape_12.setTransform(-363,30.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAKBCIgFgBIgEgBQgBgBAAAAQAAgBAAAAQAAAAAAgBQAAgBAAAAIAAhTIgBgCQgBgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAQgEAAgDgEQgDgEAAgEIACgFQABgEACgBIAEgCIAHgEIAHgFIAHgEIAGgDIAEgCQAAAAABAAQAAAAABABQAAAAABAAQABABAAAAQABABAAAAQABABAAAAQAAABABAAQAAABAAAAIAAB3QAAADgEABIgGACg");
	this.shape_13.setTransform(-373.1,30.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgQALQgBgBAAAAQgBAAAAAAQgBAAAAAAQAAgBAAAAIgDgCIgBgFIAAgCIABgDIABgDIACgCIADgBIAhAAIACABIACACIACADIAAADIgBAFQgBACgCADIgDABg");
	this.shape_14.setTransform(-378.6,30.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAKBCIgFgBIgEgBQgBgBAAAAQAAgBAAAAQAAAAAAgBQAAgBAAAAIAAhTIgBgCQgBgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAQgEAAgDgEQgDgEAAgEIACgFQABgEACgBIAEgCIAHgEIAHgFIAHgEIAGgDIAEgCQAAAAABAAQAAAAABABQAAAAABAAQABABAAAAQABABAAAAQABABAAAAQAAABABAAQAAABAAAAIAAB3QAAADgEABIgGACg");
	this.shape_15.setTransform(-385.9,30.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAKBCIgFgBIgEgBQgBgBAAAAQAAgBAAAAQAAAAAAgBQAAgBAAAAIAAhTIgBgCQgBgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAABgBAAQgBAAAAAAQgEAAgDgEQgDgEAAgEIACgFQABgEACgBIAEgCIAHgEIAHgFIAHgEIAGgDIAEgCQAAAAABAAQAAAAABABQAAAAABAAQABABAAAAQABABAAAAQABABAAAAQAAABABAAQAAABAAAAIAAB3QAAADgEABIgGACg");
	this.shape_16.setTransform(-392.5,30.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgIAJQgEgEAAgFQAAgFAEgDQADgEAFAAQAFAAAEAEQAEADAAAFQAAAFgEAEQgEAEgFAAQgFAAgDgEg");
	this.shape_17.setTransform(-403.3,36.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgCBBIgEgJIgGgPIgJgTIgJgVIgJgUIgIgSIgFgNIgCgHIACgDIAEgDIAFgCIAEAAQADgBADACQACACABADIAbBCIACABIABABQABAAAAAAQABAAAAgBQABAAAAgBQAAAAABgBIAahCIAEgFQADgBACAAIAFABIAFABIAEACIACAFIgCAFIgGANIgIATIgJAUIgJAWIgIATIgHAQIgDAIIgBACIgCABQAAAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAAAg");
	this.shape_18.setTransform(-411.9,30.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgNBDIgOgEQgGgCgGgEIgKgIQgKgKgFgMQgDgGgBgHQgCgHAAgHIACgNQABgHADgGQAFgNAKgJIAKgIIAMgHIAOgEIANgBIAOABIAOAEQAMAGAKAJQAKAJAFANQAGAMAAAOQAAAHgCAHIgEANQgFAMgKAKQgKAJgMAFIgOAEQgHACgHAAQgGAAgHgCgAgQgpQgIADgHAGQgGAHgEAIQgDAIAAAJQAAAJADAJQAEAIAGAGQAHAGAIAEQAIADAIAAQAJAAAIgDQAIgEAGgGQAHgGADgIQAEgJAAgJQAAgJgEgIQgDgIgHgHQgGgGgIgDQgIgEgJAAQgIAAgIAEg");
	this.shape_19.setTransform(-425.5,30.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAnBFQgDgBgDgDIg1hKQAAgBgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgEABQAAABgBAAQAAAAAAABQAAAAAAABQAAAAAAABIAABDQgCAEgDABIgGABIgIgBQgEAAgCgFIAAh8QAAgBABAAQAAgBAAAAQAAAAAAgBQABAAAAAAIAEgCIAEgBIAFAAQAGAAADAEIA1BIIADABIACgBIACgCIAAhDQAAAAABgBQAAAAAAgBQABAAAAgBQAAAAABAAIAEgCIAFAAIAEAAQAHAAABAFIAAB+IgDAEQgCACgEAAg");
	this.shape_20.setTransform(-440.3,30.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.date, new cjs.Rectangle(-449.5,19.4,241.1,23.3), null);


(lib.ctarectangleorangevideo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B63100").s().p("AsJC7IAAl1IYTAAIAAF1g");
	this.shape.setTransform(0,-0.3,1.024,1.048);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctarectangleorangevideo, new cjs.Rectangle(-79.6,-19.9,159.4,39.3), null);


(lib.blackwideskyscraper = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgRBA2FMAAAhsJMAiDAAAMAAABsJg");
	this.shape.setTransform(0,0,0.753,0.867);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.blackwideskyscraper, new cjs.Rectangle(-82.1,-300,164.3,600.1), null);


(lib.billboardturkey_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.billboardturkey();
	this.instance.parent = this;
	this.instance.setTransform(-178.5,-110);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.billboardturkey_1, new cjs.Rectangle(-178.5,-110,357,220), null);


(lib.billboardtableatasteof = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.billboardtable();
	this.instance.parent = this;
	this.instance.setTransform(-485,-125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.billboardtableatasteof, new cjs.Rectangle(-485,-125,970,250), null);


(lib.billboardpotatoes_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.billboardpotatoes();
	this.instance.parent = this;
	this.instance.setTransform(140,-53);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.billboardpotatoes_1, new cjs.Rectangle(140,-53,230,99), null);


(lib.billboardgreens_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.billboardgreens();
	this.instance.parent = this;
	this.instance.setTransform(-114,-60);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.billboardgreens_1, new cjs.Rectangle(-114,-60,228,120), null);


(lib.billboardcta = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AsaDGIAAmKIY1AAIAAGKg");
	this.shape.setTransform(0,19,1.002,0.993);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.billboardcta, new cjs.Rectangle(-79.6,-0.6,159.3,39.2), null);


(lib.billboardcranberries_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.billboardcranberries();
	this.instance.parent = this;
	this.instance.setTransform(-243,-33);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.billboardcranberries_1, new cjs.Rectangle(-243,-33,168,61), null);


(lib.billboardcinnamonbuns_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.billboardcinnamonbuns();
	this.instance.parent = this;
	this.instance.setTransform(-58.5,-63);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.billboardcinnamonbuns_1, new cjs.Rectangle(-58.5,-63,117,126), null);


(lib.atasteofbillboard = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhDCtQgMgEAAgJQAAgIALgEIAGgDQAGgDADgIQACgIAAgUIAAgYIAAh0IgbAAQgGABgCgDQgCgDAAgGIAAgGQAAgGACgDQADgCAFAAIAaAAIgDgTIgBgRQAAgmAXgTQAWgVAnAAQAbAAARANQARALAAAUQAAALgGAGQgGAGgMAAQgHAAgGgEQgHgDgEgHIgEgIQgJgSgOAAQgJABgFAFQgGAHAAAJIAGAbQAEAVABARIAjAAQAGgBACADQACACAAAHIAAAGQAAAGgCADQgCADgGgBIgjAAIAAB8QAAAfACAJQACAKAFADIAJADQAPAFAAAKQAAAIgMAEQgMAEgiAAQgkAAgLgEg");
	this.shape.setTransform(107,-14);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhXBaQgjgjAAg2QAAg2AlgkQAkgkA1AAQA0AAAhAiQAiAiAAA1QAAA3gkAlQgkAmg0AAQg0AAgigkgAgthHQgPATAAAhQAAAvAUAgQAVAgAcAAQAXAAAPgUQAPgUAAggQAAgvgVggQgUgggcAAQgYAAgOAUg");
	this.shape_1.setTransform(84.5,-8.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhOBbQgigjgBg0QAAg4AkgkQAjglA2AAQAvAAAbAbQAbAaAAAtQAAAPgDAFQgFAFgSAAIhcAAQgJAAgDgEQgFgEAAgHQAAgGAFgDQADgEAIAAIAzAAIALgCQADgCAAgFQAAgXgPgQQgPgQgWAAQgdAAgOAZQgOAZAAAkQAAAlATAbQATAcAfAAQARAAAMgEQANgEAMgIIAIgHQANgKAGAAQAGAAADADQAEAEgBAFQAAAFgFAJQgHAIgKAJQgVARgUAIQgTAHgXAAQgzAAgigjg");
	this.shape_2.setTransform(44.8,-8.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgMCRQgMgEgJgHQgJgJgDgMQgDgOgBglIAAiAIgVAAIgIgCIgBgGIAAgGQAAgIAZgVIAKgJIAJgIQAZgWAJAAIAHACQADACAAAEIAAAtIA2AAQAFAAADADQACABAAAIIAAAFQAAAGgCADQgDADgFAAIgzAAIgDACIgBAFIAAB4QgBAfAGAIQAFAHAOABQAIgBAMgDIAQgEQAGAAADADQAEADAAAFQAAAOgVAMQgUAMgbAAQgNAAgMgEg");
	this.shape_3.setTransform(23.6,-10.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgSB+IgZgFIgIAFIgHABIgFgBIgFgDQgIgHgHgUQgHgTAAgSQAAgIAEgFQAEgFAGAAQAMAAALATIAJAPQAHAKANAFQAMAGAOAAQAQAAAJgIQAJgIAAgOQAAgUgngUIgOgGQgmgTgNgPQgNgQAAgXQAAgfAVgUQAWgUAjAAIARABIARADIALgEIAIgCQALAAAMATQALATAAAVQAAAJgEAFQgEAEgGAAQgGAAgFgEQgGgFgHgMQgJgOgKgGQgJgGgOAAQgNAAgJAIQgIAHAAANQAAALAJAJQAIAIAeAPIACACQBEAgAAAnQAAAigaAWQgaAXgnAAg");
	this.shape_4.setTransform(4.4,-8.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AArByIgNgNIgKAFQgeAUgeAAQgjAAgWgUQgVgVAAghQAAgnAcgVQAcgVAyAAQAMAAAGADQAGAEAAAKQAAANgRgBQgXABgPAMQgOALAAAUQAAAUAMALQANAMAVAAQAXAAAKgKQAKgLAAgZIAAhcQAAgVgJgLQgJgMgRAAQgLAAgLAFQgKAFgJAMIgFAGQgPASgQABQgKgBgGgGQgFgGAAgLQAAgWAcgPQAcgQAsAAQAaAAATAHQATAHALANQAHAKADAPQADAOAAAjIAABNQAAAOACAGQADAHAFABIAHACQAPAFAAAIQAAALgQAKQgQAJgWAAQgKAAgMgMg");
	this.shape_5.setTransform(-18.5,-8.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgyCsQgOgFAAgKQAAgKAOgFQANgFABgEQADgDACgoIAChyIgBg/IgCgoQgCgGgEgCQgDgCgLAAIgKAAQgQAAgKAEQgJAEgHAJIgHAQIgIARIgHAIQgEACgEAAQgIAAgDgGQgDgHAAgOQAAggAIgUQAHgTAMAAIACAAQATADAdAAICOAAQAdAAAUgDIADAAQALAAAHATQAIAUAAAgQAAAOgEAHQgDAGgIAAIgIgCIgGgIIgHgRIgIgQQgHgJgKgEQgJgEgRAAIgKAAQgKAAgDACQgFACgBAHIgBAnIgBA/IABByQABAoADADQADAEANAFQANAFAAAKQAAAKgOAFQgNAEgmAAQglAAgNgEg");
	this.shape_6.setTransform(-47.4,-13.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AA0CtQgOgEAAgLQAAgJASgGIADgCQAHgCADgDQADgEAAgGIgFgUIgJgZIgEgIIgEgCIgTgCIgjAAIgVAAQgVAAAAgRQAAgTAWAAIALgBIAZABIAaABIgahCIgXg4IgGAAIgZA8IgZA+IgXA+QgFAOAAAJQAAAHADAFQADAFAHADIAIAEQAQAFAAAKQAAALgMAEQgNAEglAAQglAAgLgEQgNgEAAgLQAAgKAOgFIAKgFQATgLAQgqIAFgOIAihWIAJgVQAjhXAIgkQACgLAGgDQAFgDANAAQAIAAAGADQAFADAFAJIAlBQIAvByIALAcQAbBGARAJIAIADQAQAFAAAKQAAALgPAEQgOAEgrAAQgsAAgOgEg");
	this.shape_7.setTransform(-93.9,-14);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.atasteofbillboard, new cjs.Rectangle(-113.8,-44.7,227.7,61.4), null);


(lib.whitelogouse = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AqoZMQk7iEjyjzQjxjxiFk6QiKlGAAljQAAljCKlGQCFk6DxjzQDzjxE6iFQFFiKFjAAQFkAAFFCKQE7CFDxDxQDyDzCFE6QCKFGAAFjQAAFjiKFGQiFE6jyDxQjxDzk7CEQlFCKlkAAQljAAlFiKgALSMVIgBANQAAAPAKAAIAzAAQAMAAgBAKIAACUQAAAHAGACQADACAKABQAKgBAEgCQAFgCAAgIIgBiTQABgKAMAAIAxAAQALAAAAgSQAAgSgMAAIigAAQgGAAgDAIgADSONIBBBGQAHAHATABQANAAAFgFQAGgFgIgIIhOhWQgJgLAKgHIBAg6QAJgKgMgMQgMgMgNALIhKBEQgFAFgEABQgFADgKAAQgKAAAAgOIAAg2QAAgMgRAAQgMAAgDACQgFACgBAIIAAC1QAAANARAAQAVAAAAgNIAAg7QAAgGADgFQAEgEAFAAQATgBALAKgAhwOXQALAAAFAJIAhAyQAFAIARABQAPAAAEgFQAFgEgFgHIgigzQgEgFAHgHQAPgKAIgIQAOgQAAgYQABgfgVgUQgUgSggAAIhsAAQgJAAAAAIIAAC6QAAAMANAAIAPgBQAKgBAAgHIgBgxQABgEADgDQADgDAEAAgAmQOxQAIAAACAHIANAbQAEAHAPABQAIgBAGgCQAJgDgDgGIhXi7QgFgJgLAAQgMAAgEAKIhaC5QgFAMAWAAQASAAADgHIANgXQAEgLAIAAgArGNkIANBsQAAAFAGADQAFADAEAAQAYAAgBgLIgVi2QgCgIgEgDQgDgCgGAAQgLAAgEAIIg8BPQgHAIgEAAQgEABgGgIIg3hPQgGgIgKAAQgKgBgEAFQgDADgCAJIgVCxQAAAGAGADQAFADAFAAQAUAAACgLIANhpQACgIAEABQAEAAADACIAtA9QAEAHAHAAQAFAAAFgGIAwg/QADgEAEABQAFgBACAHgAGyMaIAACwQAAAOANAAICcAAQAKABAAgSQAAgSgKAAIh6AAQgJAAgBgLIAAgdQAAgLAMAAIBFAAQAKAAAAgRQABgTgLABIhHAAQgJAAgBgKIAAgbQAAgJAJAAIB6AAQAHAAADgGQABgEAAgJQAAgJgBgEQgDgEgGAAIicAAQgNAAAAANgAT4IwQgNAOABASQgBASANANQANANATAAQASAAANgNQANgNAAgSQAAgSgNgOQgNgNgSABQgTgBgNANgAP5JKQAlAMA0AAQBUAAAzgtQAygtAAhJQAAghgMgeQgMgegWgXQgUgVgXgSQgWgRgzgkIgqgdQgbgVgMgSQgJgMAAgXQAAgaARgQQASgPAeAAQAsAAAjAbQAPALAFAGQAHAIAOAVQAKAOAMAAQALABAGgHQAIgFgBgJQABgIgCgEIgUhcQgFgXgTAAQgIAAgKAGQgLAIgIAAIgMgCIgWgEQgjgIgmAAQhGAAgrAlQgrAmAAA+QAAAzAgAmQAUAVARAPIBNA3QBBAsAaAdQAcAfgBAhQABAigaAUQgaAWgpAAQglAAgigSQghgTgWgfIgMgRQgJgLgMAAQgLAAgIAIQgIAIAAALQAAAKACAHIAWBUQAEAQAFAHQAGAGALAAQAJAAALgIQAJgJAJABIASAEgAjRF+QAHAAACALIABADQAYBeBFA1QBHA2BlAAQCCAABMhQQBMhRAAiIQAAiFhMhQQhNhQh+ABQhogBhHA3QhFA1gYBgIAAABQgCALgHAAQgIAAgBgKQgYhhhHg2QhHg3hoABQiBAAhLBQQhLBQAACIQgBCFBMBQQBMBQB+AAQBoAABIg2QBHg2AYhfIAAgBQACgLAGAAIABAAgAFnIeQgGAHAAAKQAAANAJAFQAIAEAUADQBeANBrgBQBFABAxgOQAvgOAlgeQAwglAZg+QAZg9AAhOQAAhFgTg3QgVg5glgmQgngng1gSQg1gShOAAQhrAAheANQgUADgIAEQgJAFAAANQAAAJAGAIQAFAGAJABIARAAQAKAAAFALQADAKgBAXIAAF5QABAYgDAKQgFALgKAAIgRAAQgJAAgFAHgAyyIfQgHAHABAKQgBAOAJAFQAJAGAWAAICcAAQAYAAAJgGQAJgFAAgOQAAgKgHgHQgGgGgKAAIgTAAQgMAAgGgMQgCgFAAgbIgBiLQAAgZAJgFQAEgEAeAAIBGAAQAaAAAIAEQAHADACANIABAFQAEAWATABQANgBAGgIQAFgKAAgWIAAhHQAAgWgFgJQgGgJgNAAQgUAAgDAVIgBAGQgBAMgIAEQgHADgbAAIhGAAQgeAAgEgDQgJgFAAgaIAAhlQABghAIgJQAJgJAiAAIBtAAQAgAAANAEQAOAFAGAPQAFAOADAFQAIAOAOAAQAMAAAFgJQAGgJgEgQIgMg8QgFgUgZgBIlwAAQgWABgIAFQgJAGAAAOQgBAJAHAHQAHAHAIAAIASAAQAEAAAEAEQAEADABAGQAEAKAAAXIAAF8QAAAXgDAJQgEAMgKAAIgSAAQgJAAgGAGgACorXQACAKgJADQgpAOgmATQgmATgZASQg5AoggBCQgfBEAABaQgBCLBPBTQBOBUCEAAQCHAABQhVQBPhUAAiOQAAilhohNQg7gsg4AGQghAEgFAUQgFATAbAKQA2AUAZA8QAXA3ABBfQAABxgrBBQgrBChKAAQhLAAgphBQgrg/AAhyQAAhQAQg0QASg+AwgvQAegdBHgjQA9gfAigrQATgZABgVQACgTgQgEQgMgEgNANIgZAWQguAeg4gRQgvgPgjgoQgcgggogIQgcgGgfAHQgLADgEgHQgCgHAKgIQAbgVArACQAvACAfAcQAdAbAhAPQAjARAagGQARgDAAgOQABgOgTgHQgegLgng1Qgmg0g0gQQhOgWhLA9QhDA3gXBWQgGAXAMALQAMALAUgKQA7gZAuAWQAJAEAhAVQAcARAWAJQAsARA7gLIAGAAQAIAAACAHgAvDlPIBJDYQAHAXALAJQALAKATAAQATAAALgLQAKgLAJggICImzQAGgWAHgJQAIgJALgCQAkgEgBAwIAAF+QAAAbgCAHQgBAEgFADQgEADgFAAIgQAAQgJAAgHAHQgGAHgBAJQAAAOAJAGQAJAFAVAAICbAAQAVAAAIgFQAHgFABgOQAAgKgGgHQgGgHgJAAIgQAAQgLAAgFgKQgCgKAAgYIAAiBQgBgeAGgGQAFgHAYABIBzAAQAYgBAHAIQACAEABAGIAAAeIAAB8QAAAbgCAHQgGAKgJAAIgRAAQgIAAgHAHQgGAHAAAJQgBAOAJAGQAIAFAWAAICaAAQAWAAAJgFQAJgGAAgOQAAgJgHgHQgGgHgKAAIgRAAQgEAAgFgDQgEgDgBgEQgEgKAAgYIAAl+QAAgXAEgKQABgEAEgDQAFgEAEAAIARAAQAKABAGgHQAHgHAAgKQgBgOgIgFQgJgGgWAAIiaAAQgWAAgJAGQgJAFABAOQgBAKAHAHQAGAHAKgBIARAAQAKAAAFALQACAGAAAbIAABpIAAAeQgBAHgCADQgHAHgYAAIhzAAQgYAAgFgGQgGgHABgdIAAhuQAAgYACgJQAFgLALAAIAQAAQAJABAGgHQAGgHAAgKQAAgOgIgFQgIgGgVAAIkmAAQgRAAgIAGQgIAFAAANQAAAWAcABQAeAEAAATQAAAIgEAMIheE7QgCAFgEABQgEAAgCgGIhfksQgIgZgBgLQAAgMAHgEQAFgFARgCQAcgFgBgSQAAgXgcAAIinAAQgdAAgBAaQABAJAFAFQAGAFANADQAOAFAHADQAHAFADAKIAmBtQAHAYgJAZIg+C3QgCAFgEAAQgFABgCgFIh0lIQgCgLAAgIQAAgKAGgFQAGgEAOgCQARgBAGgGQAIgEgBgLQAAgXgcAAIiuAAQgdAAAAAWQAAALAFAEQAFAGANACQAVAFAHAGQAHAIAJAaICnG/QAJAXALAKQAKAJATAAQAQAAAMgJQAIgIAJgZIBOjYQABgGAEAAQAFAAABAGgAOkiCQgGAHAAAJQAAAOAJAGQAHAFAWABIFigBQAaAAAFgVIANhCQADgQgFgJQgEgJgNABQgPAAgHAPIgIAQQgPAggvAAIhUAAQgkAAgPgGQgKgEgDgLQgDgLAAgiIAAhsQAAgZAIgFQAEgDAfAAIAmAAQAbAAAHADQAIADACANIAAAFQAEAXAUAAQANAAAGgJQAEgJAAgWIAAhIQAAgVgEgJQgGgKgNAAQgUAAgEAWIAAAFQgCANgHADQgIADgbAAIgmAAQgfAAgEgCQgIgGAAgaIAAhkQAAgiAIgJQAJgIAjgBIBQAAQAfABANAEQAPAFAFAPQAGAQADACQAHAOAOAAQANAAAEgJQAGgJgEgQIgMg7QgFgVgZAAIlTAAQgVAAgJAGQgJAFAAAOQAAAJAGAIQAIAGAIAAIARAAQAEAAAEAEQAEAEACAFQADAIAAAaIAAF7QAAAagDAIQgCAEgDADQgEAEgFAAIgRAAQgJAAgGAGgAHyiCQgGAHAAAJQAAAOAJAGQAIAFAVAAIE/AAQAaAAAFgVIAMhCQAEgQgFgJQgFgJgMABQgPAAgIAPIgHAQQgQAgguAAIgxAAQgZAAgMgCQgMgBgGgFQgIgFgCgJQgCgJAAgdIAAllQABgbACgFQADgMAOAAIATAAQAJABAHgHQAGgHABgKQgBgOgIgFQgKgGgXAAIicAAQgWAAgJAGQgJAFAAAOQAAAKAHAHQAGAHAKgBIARAAQALAAADAMQADAHAAAZIAAGBQAAAXgDAIQgBAEgEADQgFAEgEAAIgRAAQgJAAgGAGg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYAaQgKgLAAgPQAAgOAKgKQAKgLAOABQAPgBAKALQAKAKAAAOQAAAPgKALQgKAJgPABQgOgBgKgJgAAWAYIgPgVQANgBAAgNQAAgPgRAAIgTAAIAAAyIAJAAIAAgVIAFAAIAOAVIAKAAg");
	this.shape_1.setTransform(130.4,59.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrAiQgFAAgEgDQgEgDAAgFIAAgtQAAgLANAAIA+AAQARAAAKAJQALAJAAAPQAAAQgLAJQgKAJgRAAg");
	this.shape_2.setTransform(-11.1,85);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgJAHIAAgNIAIAAQALAAAAAGQAAAHgNAAg");
	this.shape_3.setTransform(130.6,58);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhvCsQgog9AAhtQAAhtAog/QAog/BHAAQBGAAAoA/QAqBAAABqQAABrgpBAQgpA/hFAAQhIAAgog+g");
	this.shape_4.setTransform(-48.8,30.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgYAfQgIAAADgIIAZgyQABgDADAAQADAAACADIAZAzQABADgCACQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_5.setTransform(-44.3,88.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgtDtQgngDgNgHQgVgLAAghIAAljQAAghAKgMQAKgLAcgFIAdgDQBLAAAqA/QArA/AABvQAABxgrA/QgqA8hGAAIgJAAg");
	this.shape_6.setTransform(64.5,30);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhvCsQgog9AAhtQAAhtAog/QApg/BGAAQBFAAAqA/QApBAAABqQAABrgpBAQgpA/hGAAQhGAAgpg+g");
	this.shape_7.setTransform(6.9,30.3);

	this.instance = new lib.Path();
	this.instance.parent = this;
	this.instance.setTransform(0,0.1,1,1,0,0,0,163.5,163.5);
	this.instance.alpha = 0.59;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.whitelogouse, new cjs.Rectangle(-175,-175,350,350), null);


(lib.ctarectanglerollover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_11 = function() {
		this.stop();
	}
	this.frame_23 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(11).call(this.frame_11).wait(12).call(this.frame_23).wait(12));

	// Layer 1
	this.instance = new lib.ctarectangleorangevideo();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:1},9).wait(2).to({alpha:0},10).wait(13));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-79.6,-19.9,159.4,39.3);


// stage content:
(lib.billboardfadeatasteofseven = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_28 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_276 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(28).call(this.frame_28).wait(248).call(this.frame_276).wait(3));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(486.2,125.3,4.708,0.381,0,0,0,0.3,0.8);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(279));

	// grey-rectangle
	this.instance = new lib.greyrectangle();
	this.instance.parent = this;
	this.instance.setTransform(485,125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(279));

	// fade-from-white
	this.instance_1 = new lib.blackwideskyscraper();
	this.instance_1.parent = this;
	this.instance_1.setTransform(486.8,125.1,5.906,0.417,0,0,0,0.4,0.2);
	this.instance_1.filters = [new cjs.ColorFilter(1, 1, 1, 1, 255, 255, 255, 0)];
	this.instance_1.cache(-84,-302,168,604);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({regX:0.1,regY:0.4,x:488.7,alpha:0},9).wait(270));

	// white-logo
	this.instance_2 = new lib.whitelogouse();
	this.instance_2.parent = this;
	this.instance_2.setTransform(851.8,50.7,0.414,0.414,0,0,0,0,0.1);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({regY:0,scaleX:0.03,scaleY:0.03,y:56.7},0).to({regX:0.1,scaleX:0.47,scaleY:0.47,x:851.9,alpha:1},6).to({scaleX:0.41,scaleY:0.41,x:851.8},7).wait(257));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EgyQATTMAAAgmlMBpGAAAMAAAAmlg");
	mask.setTransform(351,120.6);

	// a-taste-of
	this.instance_3 = new lib.atasteofbillboard();
	this.instance_3.parent = this;
	this.instance_3.setTransform(143.1,84.2);
	this.instance_3.alpha = 0;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(18).to({x:-209.1,y:81.9},0).to({x:163.1,y:84.2,alpha:1},10,cjs.Ease.get(1)).to({x:143.1},6,cjs.Ease.get(1)).wait(195).to({alpha:0},5).wait(45));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("EgyQATTMAAAgmlMBpGAAAMAAAAmlg");
	mask_1.setTransform(351,120.6);

	// whole-foods-market
	this.instance_4 = new lib.wholefoodsmarket();
	this.instance_4.parent = this;
	this.instance_4.setTransform(262.3,137.6);
	this.instance_4.alpha = 0;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(18).to({x:-209.1},0).to({x:282.3,alpha:1},10,cjs.Ease.get(1)).to({x:262.3},6,cjs.Ease.get(1)).wait(75).to({alpha:0},5).wait(165));

	// Savory Sides
	this.instance_5 = new lib.savorysides();
	this.instance_5.parent = this;
	this.instance_5.setTransform(170.8,137.6);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(109).to({alpha:1},10).wait(30).to({alpha:0},5).wait(125));

	// delicious-desserts
	this.instance_6 = new lib.deliciousdessertsbillboard();
	this.instance_6.parent = this;
	this.instance_6.setTransform(233.8,137.6);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(149).to({alpha:1},10).wait(30).to({alpha:0},5).wait(85));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("EgyQATTMAAAgmlMBpGAAAMAAAAmlg");
	mask_2.setTransform(351,120.6);

	// thanksgiving
	this.instance_7 = new lib.thanksgiving();
	this.instance_7.parent = this;
	this.instance_7.setTransform(178.8,137.6);
	this.instance_7.alpha = 0;

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(189).to({alpha:1},10).wait(30).to({alpha:0},5).wait(45));

	// mask (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	mask_3.graphics.p("EgvPATTMAAAgmlMBmGAAAMAAAAmlg");
	mask_3.setTransform(351.1,120.6);

	// cta
	this.instance_8 = new lib.findanevent();
	this.instance_8.parent = this;
	this.instance_8.setTransform(110.9,195.9);
	this.instance_8.alpha = 0;

	var maskedShapeInstanceList = [this.instance_8];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(28).to({x:-55.7},0).to({x:131.5,alpha:1},10,cjs.Ease.get(1)).to({x:110.9},6,cjs.Ease.get(1)).wait(235));

	// mask (mask)
	var mask_4 = new cjs.Shape();
	mask_4._off = true;
	mask_4.graphics.p("EgyQATTMAAAgmlMBpGAAAMAAAAmlg");
	mask_4.setTransform(351,120.6);

	// cta-rollover
	this.cta_rollover = new lib.ctarectanglerollover();
	this.cta_rollover.parent = this;
	this.cta_rollover.setTransform(111.6,214.9);

	var maskedShapeInstanceList = [this.cta_rollover];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_4;
	}

	this.timeline.addTween(cjs.Tween.get(this.cta_rollover).wait(28).to({x:-55.7,alpha:0},0).to({x:131.6,alpha:1},10,cjs.Ease.get(1)).to({x:111.6},6,cjs.Ease.get(1)).wait(235));

	// mask (mask)
	var mask_5 = new cjs.Shape();
	mask_5._off = true;
	mask_5.graphics.p("EgyQATTMAAAgmlMBpGAAAMAAAAmlg");
	mask_5.setTransform(351,120.6);

	// cta-rectangle
	this.instance_9 = new lib.billboardcta();
	this.instance_9.parent = this;
	this.instance_9.setTransform(111.5,195.7);
	this.instance_9.alpha = 0;

	var maskedShapeInstanceList = [this.instance_9];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_5;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(28).to({x:-55.7},0).to({x:131.5,alpha:1},10,cjs.Ease.get(1)).to({x:111.5},6,cjs.Ease.get(1)).wait(235));

	// mask (mask)
	var mask_6 = new cjs.Shape();
	mask_6._off = true;
	mask_6.graphics.p("EgyQATTMAAAgmlMBpGAAAMAAAAmlg");
	mask_6.setTransform(351,120.6);

	// tasting-event-near-you
	this.instance_10 = new lib.tastingeventnearyou();
	this.instance_10.parent = this;
	this.instance_10.setTransform(175.3,38.3);
	this.instance_10.alpha = 0;

	var maskedShapeInstanceList = [this.instance_10];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_6;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(9).to({x:-122.1},0).to({x:195.3,alpha:1},10,cjs.Ease.get(1)).to({x:175.3},6,cjs.Ease.get(1)).wait(254));

	// mask (mask)
	var mask_7 = new cjs.Shape();
	mask_7._off = true;
	mask_7.graphics.p("EgyQATTMAAAgmlMBpGAAAMAAAAmlg");
	mask_7.setTransform(351,120.6);

	// try-new-flavors
	this.instance_11 = new lib.trynewflavors();
	this.instance_11.parent = this;
	this.instance_11.setTransform(208.7,84.2);
	this.instance_11.alpha = 0;

	var maskedShapeInstanceList = [this.instance_11];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_7;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(233).to({x:-155.5,y:81.9},0).to({x:228.7,y:84.2,alpha:1},10,cjs.Ease.get(1)).to({x:208.7},6,cjs.Ease.get(1)).wait(30));

	// mask (mask)
	var mask_8 = new cjs.Shape();
	mask_8._off = true;
	mask_8.graphics.p("EgyQATTMAAAgmlMBpGAAAMAAAAmlg");
	mask_8.setTransform(351,120.6);

	// for-your-feast
	this.instance_12 = new lib.foryourfeast();
	this.instance_12.parent = this;
	this.instance_12.setTransform(193.1,137.6);
	this.instance_12.alpha = 0;

	var maskedShapeInstanceList = [this.instance_12];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_8;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(233).to({x:-139.9},0).to({x:213.1,alpha:1},10,cjs.Ease.get(1)).to({x:193.1},6,cjs.Ease.get(1)).wait(30));

	// turkey
	this.instance_13 = new lib.billboardturkey_1();
	this.instance_13.parent = this;
	this.instance_13.setTransform(763.5,140);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(84).to({alpha:1},10).wait(185));

	// cinnamon-buns
	this.instance_14 = new lib.billboardcinnamonbuns_1();
	this.instance_14.parent = this;
	this.instance_14.setTransform(911.5,63);
	this.instance_14.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(94).to({alpha:1},10).wait(175));

	// brussel-sprouts
	this.instance_15 = new lib.billboardgreens_1();
	this.instance_15.parent = this;
	this.instance_15.setTransform(559,60);
	this.instance_15.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(71).to({alpha:1},10).wait(198));

	// cranberries
	this.instance_16 = new lib.billboardcranberries_1();
	this.instance_16.parent = this;
	this.instance_16.setTransform(449,222);
	this.instance_16.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(51).to({alpha:1},10).wait(218));

	// potatoes
	this.instance_17 = new lib.billboardpotatoes_1();
	this.instance_17.parent = this;
	this.instance_17.setTransform(238,204);
	this.instance_17.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(61).to({alpha:1},10).wait(208));

	// date
	this.instance_18 = new lib.date();
	this.instance_18.parent = this;
	this.instance_18.setTransform(479.2,137.6);
	this.instance_18.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(264).to({alpha:1},10,cjs.Ease.get(1)).wait(5));

	// table
	this.instance_19 = new lib.billboardtableatasteof();
	this.instance_19.parent = this;
	this.instance_19.setTransform(485,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_19).wait(279));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(484.6,103.1,970.4,271.9);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 970,
	height: 250,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/index_atlas_P_.png", id:"index_atlas_P_"},
		{src:"images/index_atlas_NP_.jpg", id:"index_atlas_NP_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;